### PR TITLE
all: fix typos discovered by codespell

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
```
codespell --skip .git --skip ./test | less
```

See https://github.com/codespell-project/codespell

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
```
FAIL	github.com/zalando-incubator/stackset-controller/cmd/e2e [setup failed]
FAIL
# github.com/zalando-incubator/stackset-controller/cmd/e2e
/go/pkg/mod/github.com/zalando-incubator/stackset-controller@v1.4.0/cmd/e2e/basic_test.go:9:2: github.com/stretchr/testify@v1.8.2: missing go.sum entry for go.mod file; to add it:
	go mod download github.com/stretchr/testify
```
Looks like stackset controller updated is needed

**Comment by linki** [comment]
PR for the e2e fix is already create. Let's merge this one without e2e passing.

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
