### PR TITLE
Added Roman Zavodskikh to maintainers

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
Signed-off-by: Roman Zavodskikh <roman.zavodskikh@zalando.de>

### CODE REVIEW

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by RomanZavodskikh** [comment]
My approval is not working. Creating this PR for such +1 to work. :-)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
