### PR TITLE
Rollback docker networking

### PR DESCRIPTION
**Pull request by Raffo**
This is a fix to the docker issues we are experiencing. In the future we can think of reintroducing the flag as long as the related issues are fixed.

### CODE REVIEW

**Comment by hjacobs** [comment]
So actually following recommendations from jbeda on Twitter broke stuff? :smirk:

**Comment by Raffo** [comment]
It was not Joe, but yeah :D

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
@tuxlife please comment your findings about the relevant `iptables` rules which were missing...

**Comment by tuxlife** [comment]
I think `iptables=false` disables more than the unused iptables rules. It breaks the SNAT for answers
:+1:

**Comment by tuxlife** [comment]
:+1:

**Pull request merged**
