### PR TITLE
enabling default encryption of EBS

### PR DESCRIPTION
**Pull request by jrake-revelant**
AWS allows us to encrypt data at rest by default without performance penalty. this PR enables it.

### CODE REVIEW

**Comment by jrake-revelant** [comment]
Failing probably because of [this](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html):

```
There is no direct way to encrypt an existing unencrypted volume, or to remove encryption from an encrypted volume. However, you can migrate data between encrypted and unencrypted volumes.
```

**Comment by jrake-revelant** [comment]
@mikkeloscar this was never merged anywhere else, was it?

**Comment by mikkeloscar** [comment]
@jrake-revelant no it wasn't, but we can probably enable this globally per account instead of just for the cluster components.

**Comment by mikkeloscar** [comment]
Closing this since we will enable EBS encryption at the account level.

**Pull request closed without merging**
