### PR TITLE
fix ghost ASGs issue

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Fix for the broken ingress controller: https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/250

I also think we should run it without the `-quiet` flag, because otherwise it doesn't log any actions it takes.

**Comment by szuecs** [comment]
removed --quiet and update to hotfix release

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
