### PR TITLE
Run one karpenter pool in e2e

### PR DESCRIPTION
**Pull request by mikkeloscar**
Run a karpenter pool and a single pod as part of e2e to verify that basic karpenter setup works.

### CODE REVIEW

**Comment by demonCoder95** [comment]
👍

**Comment by myaser** [comment]
👍🏻

**Comment by myaser** [comment]
👍🏻

**Comment by myaser** [comment]
👍🏻

**Comment by gargravarr** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
