### PR TITLE
hotfix for kubelet

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Closing in favor of: https://github.com/zalando-incubator/kubernetes-on-aws/pull/1780

**Comment by mikkeloscar** [comment]
So I somehow messed up #1780 and dropped this change..

**Comment by aermakov-zalando** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
