### PR TITLE
Remove initial flannel config from userdata

### PR DESCRIPTION
**Pull request by linki**
* pod network should work without the initial config in the userdata

### CODE REVIEW

**Comment by szuecs** [comment]
@linki do we have benefits from the new version? Some bugfixes that you could link here?

I would postpone the rollout to the next userdata update, thoughts?

**Comment by linki** [comment]
@szuecs New version was merged in the last PR already.

This removes some userdata content that isn't really needed anymore. It's fine to wait and be combined with other stuff. Or even better: reduce the userdata to not have this discussion.

**Comment by szuecs** [comment]
:+1: dev-to-alpha was already opened, so we can merge this

**Comment by szuecs** [comment]
:+1:

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
