### PR TITLE
Dev to alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Kubernetes-dashboard updated to v1.6.1 (#420)
* Update kubelet flags (#418, #423)
* Add traffic switching support for skipper (#421)
* Update ingress-controller to use CF (#419, #417)

### CODE REVIEW

**Comment by Raffo** [comment]
I would wait for #423 to be in all dev clusters before merging this.

**Comment by mikkeloscar** [comment]
> I would wait for #423 to be in all dev clusters before merging this.

Sure, now it's just ready. (Added do-not-merge label).

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ideahitme** [comment]
👍

**Pull request merged**
