### PR TITLE
switch metrics to LS endpoint

### PR DESCRIPTION
**Pull request by vetinari**
otherwise collectors get quite some traffic on top

### CODE REVIEW

**Comment by macedigital** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ghost** [comment]
Please hold merging this PR for now. We are discussing the need for these changes.

**Comment by ghost** [comment]
Please proceed with merging this PR. Thank you for your help here 🧡

**Comment by demonCoder95** [comment]
👍

**Pull request merged**
