### PR TITLE
Bump kube2iam to v0.5.2

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update to v0.5.2

https://github.com/jtblin/kube2iam/releases/tag/0.5.2

### CODE REVIEW

**Comment by hjacobs** [comment]
Restarted e2e as the first run was failing (I suppose AWS rate limits).

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Seems to work fine as I can see these log lines in e2e (i.e. ALB can be create and thus kube2iam works):

```
[1mSTEP[0m: ALB endpoint from ingress status: l-1-kube-aws-test-e2e169-123-1350216126.eu-central-1.elb.amazonaws.com
[1mSTEP[0m: Waiting for skipper route to default redirect from http to https, to see that our ingress-controller and skipper works
[1mSTEP[0m: Waiting for ALB to create endpoint l-1-kube-aws-test-e2e169-123-1350216126.eu-central-1.elb.amazonaws.com and skipper route, to see that our ingress-controller and skipper works
[1mSTEP[0m: Waiting for DNS to see that mate and skipper route to service and pod works

**Comment by Raffo** [comment]
👍

**Pull request merged**
