### PR TITLE
Update deployment-service to include validate api

### PR DESCRIPTION
**Pull request by linki**
This adds the `/validate` endpoint to each cluster's local deployment-status service.

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
👎  there's a follow up

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by demonCoder95** [comment]
👍

**Pull request merged**
