### PR TITLE
fix redirect handling for path routes

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Would the `routesrv` also need to be updated for these cases where it's related to the routes to be sure both of them align?

**Comment by szuecs** [comment]
@mikkeloscar good catch :)

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
please update this, too:

```
tag=artifact=registry.opensource.zalan.do/teapot/skipper-internal:v0.13.108-177
```

**Comment by szuecs** [comment]
@aryszka we can do this when we enable opentracing.

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
