### PR TITLE
feature: allow cluster access for deployment-discovery (#1817)

### LINKED ISSUE #1817: Allow kubernetes access for `deployment-discovery` application
This service substitutes the `api-discovery-k8s` application.

### PR DESCRIPTION
**Pull request by tkrop**
fixes #1817.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
Please use the new token version (which would give you a STUPS-compatible `uid`).

**Comment by tkrop** [comment]
You mean changing `apiVersion: "zalando.org/v1"` to `apiVersion: "zalando.org/v2"`?

I cannot find any documentation about the implications this will have. Can you elaborate?

**Comment by mikkeloscar** [comment]
I sent you the link to our internal docs on this.

**Comment by tkrop** [comment]
App is updated.

**Comment by mikkeloscar** [comment]
@tkrop you need to update the application uid to: `stups_<application>` in this PR.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
