### PR TITLE
Make Network CIDR used for etcd security groups configurable

### PR DESCRIPTION
**Pull request by mikkeloscar**
cherry-pick for beta to roll out the etcd-stack changes needed before the new CLM version can be rolled out.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
One test pending because the jenkins node died while deleting the cluster. Test ran successfully:

```
Ran 4 of 538 Specs in 395.328 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 534 Skipped PASS
```

**Comment by szuecs** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
