### PR TITLE
Update to Kubernetes v1.7.3

### LINKED ISSUE #514: static pods not registered with api server
Since upgrading to kubernetes 1.7 static pods (apiserver, scheduler, ...) cannot be registered with the api server (mirror pods).

```
Jul 28 08:50:47 ip-172-31-16-25.eu-central-1.compute.internal kubelet-wrapper[936]: E0728 08:50:47.537800     936 kubelet.go:1607] Failed creating a mirror pod for "kube-controller-manager-ip-172-31-16-25.eu-central-1.compute.internal_kube-system(35d2d3b729826258ed71101e688b6bf4)": pods "kube-controller-manager-ip-172-31-16-25.eu-central-1.compute.internal" is forbidden: no providers available to validate pod request
Jul 28 08:50:57 ip-172-31-16-25.eu-central-1.compute.internal kubelet-wrapper[936]: E0728 08:50:57.581996     936 kubelet.go:1607] Failed creating a mirror pod for "kube-proxy-ip-172-31-16-25.eu-central-1.compute.internal_kube-system(2908bf33d480a29f35190eda0d4f912b)": pods "kube-proxy-ip-172-31-16-25.eu-central-1.compute.internal" is forbidden: no providers available to validate pod request
```

I think this error usually happended when there's no PSP for the pod. @szuecs can confirm this.

### PR DESCRIPTION
**Pull request by mikkeloscar**
Reintroduce v1.7.2. Original PR: #496.

~This is work in progress as we need to fix #514 and #518 before this is ready to be merged.~

Fixes #514, #518

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Updated this to Kubernetes v1.7.3

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v173

**Comment by linki** [comment]
Sweet, they are passing!

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
Only had to add/remove the 'ready-to-test' label a few times lol :D

**Comment by hjacobs** [comment]
@mikkeloscar room for improvements? :smirk:

**Comment by mikkeloscar** [comment]
> @mikkeloscar room for improvements?

Sure, but now the e2e tests are correctly configured, which was the problem here :)

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
