### PR TITLE
Use a custom flannel image so it's always killed

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Mitigates https://github.com/coreos/flannel/issues/1002.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
@aermakov-zalando can you create an upstream PR for flannel with the fix?

**Comment by aermakov-zalando** [comment]
@hjacobs I didn't fix the problem in flannel, just added a workaround.

**Comment by gargravarr** [comment]
:+1:

**Comment by notxcain** [comment]
@aermakov-zalando could you please describe the workaround you've used?

**Comment by aermakov-zalando** [comment]
@notxcain we just kill `flannel` instead of letting it terminate gracefully.

**Comment by linki** [comment]
@notxcain ...so that it doesn't have a chance to execute any shutdown action, which in our case somehow triggered some undesireable effects.

**Comment by notxcain** [comment]
@aermakov-zalando I see, thanks. In our case flannel doesn't terminate, writes `shutdownHandler sent cancel signal...` to log and network stops working.

**Pull request merged**
