### PR TITLE
Update kube-metrics-adapter

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Changes:
 * Fade-in/fade-out for scheduled scaling metrics (https://github.com/zalando-incubator/kube-metrics-adapter/pull/370)

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Should we make the timeout configurable with a config item? I realize the default is 10 min. but in case we want to tweak it later on.

**Comment by aermakov-zalando** [comment]
We could, of course, although I don't see us tweaking it in the future.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
