### PR TITLE
ingress controller with health period of 10s

### PR DESCRIPTION
**Pull request by hjacobs**
Set ALB health period to 10s to become unhealthy within default pod grace period (30s).

See https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/48

### CODE REVIEW

**Comment by hjacobs** [comment]
e2e test failure: "Should create valid https and http ALB endpoint [Ingress] [Zalando]"

@szuecs can you check whether this is caused by the PR or a flake / 1.6 issue?

**Comment by mikkeloscar** [comment]
> @szuecs can you check whether this is caused by the PR or a flake / 1.6 issue?

Timeout was too low, I bumped it from 2 min. to 5 min.

**Comment by hjacobs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
