### PR TITLE
Update prometheus to v2.9.1

### PR DESCRIPTION
**Pull request by mikkeloscar**
https://github.com/prometheus/prometheus/releases/tag/v2.9.0

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Updated to v2.9.1: https://github.com/prometheus/prometheus/releases/tag/v2.9.1

It adds two relevant bugfixes:

```
[BUGFIX] Discovery/kubernetes: fix missing label sanitization #5462
[BUGFIX] Remote_write: Prevent reshard concurrent with calling stop #5460
```

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
I think remote write is not important for us. ;)

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
