### PR TITLE
beta-to-stable

### PR DESCRIPTION
**Pull request by njuettner**
* **alpha-to-beta**
   <sup>Merge pull request #1950 from zalando-incubator/alpha-to-beta</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1948 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Put ingress-template-controller behind feature toggle to gradually decommission it**
   <sup>Merge pull request #1899 from zalando-incubator/toggle-ingress-template-controller</sup>

### CODE REVIEW

**Comment by njuettner** [comment]
👍

**Comment by tkrop** [comment]
can we please get #1956 and #1960 onto the next train.

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
@tkrop as long we do not need a node change, everything is not a problem to roll out.

**Pull request merged**
