### PR TITLE
Adding ClusterRoles for the three Fabric operators:

### PR DESCRIPTION
**Pull request by cjbooms**
Fabric Gateway
Fabric Event Streams
Sloppy

### CODE REVIEW

**Comment by mikkeloscar** [comment]
FYI: this is being done to avoid chicken and egg problems for Fabric tools which are deployed to every cluster anyway.

Without these roles they need to create the CRD before creating the role which is problematic as they have two projects depending on each other (metacontroller and their own controller).

**Comment by mikkeloscar** [comment]
:+1:

**Comment by cjbooms** [comment]
👍

**Comment by herojan** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by herojan** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
