### PR TITLE
update ExternalDNS to v0.4.0

### PR DESCRIPTION
**Pull request by linki**
uses the released 0.4 version of ExternalDNS

### CODE REVIEW

**Comment by hjacobs** [comment]
:tada: but e2e fails..

**Comment by linki** [comment]
https://github.com/zalando-incubator/kubernetes-on-aws/pull/500 needs to be merged first. CLM omits a config item which is still required in this state. We could have easily used both config items in parallel or have some backwards compatibility in image policy webhook. Learning for next time.

**Comment by linki** [comment]
👍

**Comment by gargravarr** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
