### PR TITLE
Enable 1.18 CA by default in all test clusters

### PR DESCRIPTION
**Pull request by aermakov-zalando**
We haven't had any issues in the current set, let's extend it to more clusters.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by linki** [comment]
We also need to drop usage of the configitem if we remove it: https://github.com/zalando-incubator/kubernetes-on-aws/blob/12a97f2666708eeb823ea91e0e9bc85365f3ae6c/cluster/manifests/kube-cluster-autoscaler/daemonset.yaml#L71

I kept it in case the artificial scale-up doesn't work correctly.

**Comment by aermakov-zalando** [comment]
@linki For some reason `ack` didn't show it for me so I thought we've already dropped this.

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
@aermakov-zalando Shouldn't we enable `EvenPodsSpread` along with CA 1.18? https://github.com/zalando-incubator/kubernetes-on-aws/blob/ec8a08d3b7a31fcf53a614c059ce1115fd603be3/cluster/config-defaults.yaml#L400

**Pull request merged**
