### PR TITLE
Allow CDP to deploy pods everywhere

### PR DESCRIPTION
**Pull request by jmcs**
The CDP project needs to be able to deploy pods in every cluster for the deployment process.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
FYI: our e2e tests doesn't work when the branch is on a fork, that's why it's failing, I think it's reasonable to test this in `dev`.

**Comment by Raffo** [comment]
👍

**Comment by njuettner** [comment]
👍

**Comment by ideahitme** [comment]
@here need to change Poweruser to PowerUser, don't think authnz webhook does string lowercasing

**Pull request merged**
