### PR TITLE
Update zmon-worker deployment

### PR DESCRIPTION
**Pull request by mohabusama**
Changes:

- Increase number of processes to 32
- Increase number of replicas to 4
- Increase cpu requests/limit
- Upgrade zmon-worker to zv225 with EBS wrapper and Hipchat notification link

### CODE REVIEW

**Comment by szuecs** [comment]
@mohabusama is zmon-worker CPU bound?
If so did you considered an hpa?

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by mohabusama** [comment]
@szuecs I wouldn't consider it CPU bound, but I only increased the requests/limits as I increased the number of processes. I would need to investigate this further.

We wanted to use HPA indeed, but haven't given it time yet. One option is to trigger based on redis queue length.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
> One option is to trigger based on redis queue length.

This would be good, but I think increasing the number of workers manually is good enough for now.

**Comment by aermakov-zalando** [comment]
@mohabusama: please check the memory request & limits as well. It's not a good idea to keep them different unless you have bursty workloads, and zmon-worker has been running at 200% of request (and close to limit) recently.

**Comment by aermakov-zalando** [comment]
According to the statistics, 32 processes doesn't work since the pods are getting OOM killed in a day or less, so more investigation is needed.

**Comment by aermakov-zalando** [comment]
Also, HPA should definitely be investigated since the amount of resources varies a lot between the clusters. We don't want to have zmon-worker consume 32GB of memory in every single cluster just because one of them needs it.

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
