### PR TITLE
Upgrade zmon-agents

### PR DESCRIPTION
**Pull request by mohabusama**
Changes:

*zmon-aws-agent*:
- Fix instance events flapping values
- Upgrade zmon-cli with improper timeout bug

*zmon-agent-core*:
- Upgrade zmon-cli with improper timeout bug

### CODE REVIEW

**Comment by mohabusama** [comment]
@Raffo @aermakov-zalando This is the timeout fix: https://github.com/zalando-zmon/zmon-cli/pull/74/files

You earned 3.5 minutes of un-interrupted ranting about ZMON/Python/Whatever frustrates you
😄

**Comment by Raffo** [comment]
3.5 minutes each I hope! 

Labelling this ready to test.

**Comment by Raffo** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
