### PR TITLE
Fix templating in userdata

### PR DESCRIPTION
**Pull request by mikkeloscar**
Fixes an issue introduced in #1074. This was not caught by the e2e tests because they are not yet testing the new node-pool implementation.

Once all clusters has node pools we can fix the e2e.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
**Not running e2e tests on this because they would not test this change**

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
