### PR TITLE
alpha-to-beta

### PR DESCRIPTION
**Pull request by szuecs**
* **Dev to alpha**
   <sup>Merge pull request #1657 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **vpa is enabled by default no need to guard it anymore**
   <sup>Merge pull request #1655 from zalando-incubator/cleanup/vpa-is-enabled</sup>
* **optimize resource kubernetes-lifecycle-metrics**
   <sup>Merge pull request #1654 from zalando-incubator/optimize/resource-klm</sup>
* **Update kube-job-cleaner**
   <sup>Merge pull request #1656 from zalando-incubator/update-job-cleaner</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1653 from zalando-incubator/dev-to-alpha</sup>
* **enhance opentracing to investigate application and setup errors**
   <sup>Merge pull request #1650 from zalando-incubator/skipper/enhance-opentracing</sup>
* **disallow privilege escalation for restricted policy**
   <sup>Merge pull request #1641 from zalando-incubator/disable-privileged</sup>
* **fix skipper swarm communication**
   <sup>Merge pull request #1651 from zalando-incubator/fix/skipper-swarm-deployconfig</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Updating logging-agent tag**
   <sup>Merge pull request #1642 from zalando-incubator/logging-agent-tag-update</sup>
* **Grant zmon system serviceaccount**
   <sup>Merge pull request #1652 from zalando-incubator/grant-zmon-system-access</sup>
* **alb controller update v0.8.1 adds SG support **
   <sup>Merge pull request #1647 from zalando-incubator/feature/alb-sg-support</sup>
* **Don't use spot_price**
   <sup>Merge pull request #1649 from zalando-incubator/remove-spot-pricing</sup>
* **Update the VPA to version 0.3.0**
   <sup>Merge pull request #1643 from zalando-incubator/update-vpa-0.3.0</sup>
* **Adding ExternalDNS and emergency-access-service**
   <sup>Merge pull request #1648 from zalando-incubator/guaranteed</sup>
* **update to v1.11.6 will fix the node loosing IPs issue **
   <sup>Merge pull request #1632 from zalando-incubator/update/v1.11.6</sup>
* **Force system stuff to Guaranteed**
   <sup>Merge pull request #1646 from zalando-incubator/guaranteed</sup>
* **Switch privileged components to system service account**
   <sup>Merge pull request #1640 from zalando-incubator/switch-to-system-sa</sup>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👎

**Comment by aermakov-zalando** [comment]
ZMON was broken by (I think) #1652, we need to fix it first.

**Comment by aermakov-zalando** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
