### PR TITLE
Alpha to beta

### PR DESCRIPTION
**Pull request by szuecs**
* activate daemonset flannel
* schedule flannel daemonset to run on masters
* remove limits from masters, which improves latency of apiserver response times a lot
* enable support for creating internet-facing and internal ingress ALBs

### CODE REVIEW

**Comment by szuecs** [comment]
Let's merge it on Monday

**Comment by szuecs** [comment]
:+1:

**Comment by Raffo** [comment]
I would recommend to update the PR or cherry pick https://github.com/zalando-incubator/kubernetes-on-aws/pull/800

**Comment by mikkeloscar** [comment]
I think we can update it to include everything currently in alpha?

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
