### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Create default PDBs with maxUnavailable: 1
* Make it possible to not downgrade docker
* Enable non-ready-ttl for pdb-controller
* Bump ExternalDNS to v0.5.1
* add channel handling scripts
* Update ZMON components
* Add config items for all ZMON components
* Add VPA control plane #1037

### CODE REVIEW

**Comment by hjacobs** [comment]
The PR description looks pretty messy, maybe the script should use bullet points?

**Comment by mikkeloscar** [comment]
I think we want to somehow get the PR titles and group the commits under that.

**Comment by szuecs** [comment]
I thought I pull only comments and filter the most garbage out and the PR creator can prepare the rest.

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
