### PR TITLE
Bumped pdb-controller to v0.0.2 and added debug mode

### PR DESCRIPTION
**Pull request by Raffo**
Bumped pdb-controller to v0.0.2 and added debug mode. Tested manually, no need to trigger e2e.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
also bump the version labels :)

**Comment by Raffo** [comment]
Done, thank you @mikkeloscar  :-)

**Comment by linki** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
