### PR TITLE
Kubernetes v1.19.10

### PR DESCRIPTION
**Pull request by jonathanbeber**
- Updates kubernetes to [v1.19.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.19.10)
- Updates docker-ce to version 20.10.6
- Updates containerd.io to version 1.4.3-1

### CODE REVIEW

**Comment by jonathanbeber** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
Might want to list the rest of the changes as well, and update the e2e dependencies.

**Comment by jonathanbeber** [comment]
I was trying to update the e2e dependencies but it broke in some strange way. I will try to get back to it later.
You're right, I updated the description to mention the dependencies update.

**Comment by aermakov-zalando** [comment]
Let's merge it like this then, it's unlikely that 1.19.10 has major e2e changes.

**Comment by aermakov-zalando** [comment]
👍

**Comment by jonathanbeber** [comment]
:+1:

**Pull request merged**
