### PR TITLE
Update EC2 AMI to the latest versions

### PR DESCRIPTION
**Pull request by linki**
Update the AMI, recreate of #3228

### CODE REVIEW

**Comment by arjunrn** [comment]
:+1:

**Comment by szuecs** [comment]
:-1:

**Comment by szuecs** [comment]
we need to wait for https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.17.md#changelog-since-v1175

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
