### PR TITLE
skipper: disable image-updater-bot for main image

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
image-updater-bot replaces all matching image urls in the manifest so use print template function to disable it for main image.

Follow up #8193

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
> image-updater-bot replaces all matching image urls in the manifest so use print template function to disable it for main image.

See example https://github.com/zalando-incubator/kubernetes-on-aws/pull/8205

**Comment by AlexanderYastrebov** [comment]
> image-updater-bot replaces all matching image urls in the manifest so use print template function to disable it for main image.

Here is an example when it worked properly because main image url was different from canary
https://github.com/zalando-incubator/kubernetes-on-aws/pull/8220/commits/71a794b8bb7ca2e08a00b7680bcfe9a231aecbea

**Comment by RomanZavodskikh** [comment]
https://github.com/zalando-incubator/kubernetes-on-aws/pull/8220/files advances only canary image, so I guess we can move on like this and find some way to make the description of it more informative.

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
