### PR TITLE
Master nodes: enable T2 unlimited

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* Switch master node pool to use LaunchTemplate instead of LaunchConfiguration
* Automatically enable T2 unlimited for master nodes

**Note**: depends on https://github.com/zalando-incubator/cluster-lifecycle-manager/pull/66!

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@aermakov-zalando Why not add it to all node pools while we are at it? Want to test it on masters first?

**Comment by aermakov-zalando** [comment]
@mikkeloscar I wanted to experiment on masters first, yeah. We also don't use T2 for worker nodes, so the switch to launch templates there isn't that critical.

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
