### PR TITLE
alpha-to-beta

### PR DESCRIPTION
**Pull request by mikkeloscar**
* **dev-to-alpha**
   <sup>Merge pull request #1664 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **fix user errors in config for skipper ratelimit headers**
   <sup>Merge pull request #1660 from zalando-incubator/skipper/fix-ratelimit-header-cfg</sup>
* **Cadvisor daemonset**
   <sup>Merge pull request #1635 from zalando-incubator/cadvisor-daemonset</sup>
* **Update prometheus to 2.6.0**
   <sup>Merge pull request #1659 from zalando-incubator/prom-2.6.0</sup>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Should we pick up #1667 as well?

**Comment by mikkeloscar** [comment]
Sure we can add that, but it can also come later, since it's very quick to roll out.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@aermakov-zalando is it ok if we just merge this and add #1667 in a separate PR?

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
