### PR TITLE
appdynamics needs pull secrets

### PR DESCRIPTION
**Pull request by linki**
forces appdynamics to use the correct secrets

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
@linki how does it work? Isn't this still prone to a race-condition? (Just trying to understand why this fix works)

**Comment by mikkeloscar** [comment]
@hjacobs normally we just reference the `imagePullSecret` in the default service account. Here the race occurs because the default service account is attached to the pod before it has the `imagePullSecret`, thus the pod doesn't "inherit" any `imagePullSecret`s from the service account.

So by defining the `imagePullSecret` directly on the pod it doesn't need to inherit it from the service account, and the pod will not be scheduled before the actual `imagePullSecret` has been created.

**Comment by linki** [comment]
sorry for not explaining it right way. @mikkeloscar is right, that was the original idea of the fix. turns out that it behaves differently: the pod is scheduled without `imagePullSecrets` and fails as before. but since it now has a direct reference to the `secret` kubernetes will eventually apply it to the pod. (maybe when `secretary` overwrites the `secret` every two minutes this triggers some kind of resync.)

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
