### PR TITLE
add requests and limits based on current hackweek cluster

### PR DESCRIPTION
**Pull request by szuecs**
do not change the default from vendors if they set requests or limits, but make sure we have always requests and limits

added yerken to authorized_keys

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@szuecs can you add a short note about how you came up with these limit values? I think that could be useful in the feature if we ever want to understand why those were chosen.

**Comment by szuecs** [comment]
@mikkeloscar Sure!

I added requests as in hackweek was used and added a limit which I think could be reasonable for all pods. For example for node_exporter I did:

    kubectl get pods -n kube-system | grep exporter
    kubectl top pods -n kube-system --containers prometheus-node-exporter-5jzio --containers

I know this is not "measuring", but measuring is hard and have no production yet, so we have to first "understand" and "break" until we get realistic requests and limits.

**Comment by Raffo** [comment]
Before merging, should we create a cluster and try to make "a lot of load" on it? I don't see other way to prove that they are reasonable (which doesn't still mean that they will be perfect or completely realistic).

**Comment by szuecs** [comment]
Cluster create works now

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
#125 make sure system relevant PODs have enough resources with requests and limits

**Comment by Raffo** [comment]
👍

**Pull request merged**
