### PR TITLE
Improve changelog generated by prepare-pr.sh

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* Ignore all non-merge commits, since we don't squash
* Print the body first, as a markdown list item, then the subject (so we still have the PR number)

For example, #1120 will produce this instead:
> dev-to-alpha
>* **Update zmon-worker**
>   <sup>Merge pull request #1119 from zalando-incubator/update-zmon-worker</sup>
>* **redo DNS step1 - enable fallback to coredns**
>   <sup>Merge pull request #1115 from zalando-incubator/rollout/redo-dns-step1</sup>
>* **Reduce the memory scaling coefficient to 0.85**
>   <sup>Merge pull request #1117 from zalando-incubator/autoscaling-reduce-buffer-size-2</sup>
>* **Set default memory scale to 0.9**
>   <sup>Merge pull request #1116 from zalando-incubator/autoscaling-reduce-buffer-size</sup>
>* **Add muaaz's pubkey to node pools**
>   <sup>Merge pull request #1111 from zalando-incubator/muaaz-key2</sup>
>* **Use dnsPolicy: Default for cluster autoscaler**
>   <sup>Merge pull request #1109 from zalando-incubator/autoscaler-dns</sup>
>* **Move the logging-agent secret as well**
>   <sup>Merge pull request #1110 from zalando-incubator/fix-agent-dev</sup>
>* **Minor doc updates**
>   <sup>Merge pull request #1105 from zalando-incubator/doc-improvements</sup>
>* **adding muaaz ssh key**
>   <sup>Merge pull request #1104 from zalando-incubator/muaaz-ssh</sup>
>* **Autoscaling: resize buffer pods based on instance type**
>   <sup>Merge pull request #1088 from zalando-incubator/autoscaling-instance-types</sup>
>* **Update kube-job-cleaner**
>   <sup>Merge pull request #1102 from zalando-incubator/kube-job-cleaner</sup>
>* **Add missing priority classes on system components**
>   <sup>Merge pull request #1103 from zalando-incubator/add-more-priorities</sup>
>* **Fix critical logging pods**
>   <sup>Merge pull request #1098 from zalando-incubator/fix-critical-pods</sup>
>* **update skipper to add timeouts to calls to apiserver**
>   <sup>Merge pull request #1097 from zalando-incubator/fix/skipper-hang-in-apiserver-call</sup>
>* **Skip unauthorized audit events**
>   <sup>Merge pull request #1093 from zalando-incubator/skip-unauthorized-audit-events</sup>
>* **eas: Expose expiry time in GET /access-requests**
>   <sup>Merge pull request #1094 from zalando-incubator/eas-expiry</sup>
>* **Update Emergency Access Service to include list access requests endpoint**
>   <sup>Merge pull request #1087 from zalando-incubator/eas-list-pending-requests</sup>

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
What about:

```
* Title
  > Merge pull ..
```

Then it's maybe a bit easier to read the titles? :)

**Comment by aermakov-zalando** [comment]
Another option:

* **Update zmon-worker**
   <sup>Merge pull request #1119 from zalando-incubator/update-zmon-worker</sup>
* **redo DNS step1 - enable fallback to coredns**
   <sup>Merge pull request #1115 from zalando-incubator/rollout/redo-dns-step1</sup>
* **Reduce the memory scaling coefficient to 0.85**
   <sup>Merge pull request #1117 from zalando-incubator/autoscaling-reduce-buffer-size-2</sup>
* **Set default memory scale to 0.9**
   <sup>Merge pull request #1116 from zalando-incubator/autoscaling-reduce-buffer-size</sup>
* **Add muaaz's pubkey to node pools**
   <sup>Merge pull request #1111 from zalando-incubator/muaaz-key2</sup>
* **Use dnsPolicy: Default for cluster autoscaler**
   <sup>Merge pull request #1109 from zalando-incubator/autoscaler-dns</sup>
* **Move the logging-agent secret as well**
   <sup>Merge pull request #1110 from zalando-incubator/fix-agent-dev</sup>
* **Minor doc updates**
   <sup>Merge pull request #1105 from zalando-incubator/doc-improvements</sup>
* **adding muaaz ssh key**
   <sup>Merge pull request #1104 from zalando-incubator/muaaz-ssh</sup>
* **Autoscaling: resize buffer pods based on instance type**
   <sup>Merge pull request #1088 from zalando-incubator/autoscaling-instance-types</sup>
* **Update kube-job-cleaner**
   <sup>Merge pull request #1102 from zalando-incubator/kube-job-cleaner</sup>
* **Add missing priority classes on system components**
   <sup>Merge pull request #1103 from zalando-incubator/add-more-priorities</sup>
* **Fix critical logging pods**
   <sup>Merge pull request #1098 from zalando-incubator/fix-critical-pods</sup>
* **update skipper to add timeouts to calls to apiserver**
   <sup>Merge pull request #1097 from zalando-incubator/fix/skipper-hang-in-apiserver-call</sup>
* **Skip unauthorized audit events**
   <sup>Merge pull request #1093 from zalando-incubator/skip-unauthorized-audit-events</sup>
* **eas: Expose expiry time in GET /access-requests**
   <sup>Merge pull request #1094 from zalando-incubator/eas-expiry</sup>
* **Update Emergency Access Service to include list access requests endpoint**
   <sup>Merge pull request #1087 from zalando-incubator/eas-list-pending-requests</sup>

**Comment by aermakov-zalando** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
