### PR TITLE
Revert "API server: increase the ELB timeout"

### PR DESCRIPTION
**Pull request by szuecs**
Reverts zalando-incubator/kubernetes-on-aws#1732

### CODE REVIEW

**Comment by szuecs** [comment]
@mikkeloscar @aermakov-zalando you merged a PR that I disagree with  #1732 , which might work most of the time, but can create a lot of harm, because everyone thinks it just works forever.
This will lead to disaster!

**Comment by mikkeloscar** [comment]
@szuecs Sorry. I understood from your [comment](https://github.com/zalando-incubator/kubernetes-on-aws/pull/1732#discussion_r249050157) that you were ok with the change. As this was wrongly understood I'm fine with reverting this and have a separate discussion before we consider any changes to the configuration.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
Thanks @mikkeloscar

**Pull request merged**
