### PR TITLE
Dev to alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Switch to CLC/Ignition based userdata (#838)

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Comment by mikkeloscar** [comment]
Let's roll this out Thursday!

**Comment by hjacobs** [comment]
@mikkeloscar today is Thursday :smirk:

**Comment by mikkeloscar** [comment]
@hjacobs forgot about this yesterday, but it's more fun on a Friday!

**Pull request merged**
