### PR TITLE
Introduce a problematic DNS and ExternalDNS version with the fix

### PR DESCRIPTION
**Pull request by linki**
Let's add a Service of `Type: LoadBalancer` giving it a DNS name that ExternalDNS has problems with (as of `v0.13.1`, it might be fixed in later versions)

The idea is that DNS should be pretty broken when running e2e tests. Then we can see if introducing https://github.com/zalando-incubator/kubernetes-on-aws/pull/5602 makes sure to ignore the bad record.

### CODE REVIEW

**Comment by linki** [comment]
This successfully blocks all ExternalDNS updates 💥

**Comment by linki** [comment]
Now trying the same with an ExternalDNS version that should tolerate some broken records. This is hopefully green.

**Comment by linki** [comment]
So this is green now. It means a single broken record doesn't block ExternalDNS and hence it passes all e2e tests. We should try to get https://github.com/kubernetes-sigs/external-dns/pull/1209 merged or run a fork.

**Comment by linki** [comment]
As discussed let's go ahead with our internally released version from https://github.com/kubernetes-sigs/external-dns/commit/a18bf2b51258302403b2b5f081f236f8fb73e433 which includes https://github.com/kubernetes-sigs/external-dns/pull/1209. Dropping the `do-not-merge` label.

**Comment by katyanna** [comment]
:+1:

**Comment by linki** [comment]
👍

**Pull request merged**
