### PR TITLE
Pull several images from the new registry

### PR DESCRIPTION
**Pull request by linki**
Migrate over some images to the new registry.

Note, I sneaked in the new coredns version: https://github.bus.zalan.do/teapot/coredns-pipeline/pull/18

### CODE REVIEW

**Comment by demonCoder95** [comment]
👍

**Comment by demonCoder95** [comment]
container-registry.zalando.net is the domain name for the ECR, right?

**Comment by linki** [comment]
@mikkeloscar Changelog from coredns:

> Wildcard queries are no longer supported by the kubernetes plugin.

Does this affect us?

**Comment by mikkeloscar** [comment]
I can't imagine anything depends on this.

For reference this is the removal in coredns which explains what the feature was: https://github.com/coredns/coredns/pull/5019/files

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
@demonCoder95 Yes, correct. But it's a "vanity" name that gets expanded [by the real hostname of ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html) upon deployment.

**Comment by linki** [comment]
👍

**Pull request merged**
