### PR TITLE
Add the compliance monitoring app

### PR DESCRIPTION
**Pull request by aermakov-zalando**
The app is `oxygen`, read-only access only.

### CODE REVIEW

**Comment by harti2006** [comment]
:+1:

**Comment by mrandi** [comment]
:+1:

**Comment by roskenet** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
Why do we allow "funny" app names again? We should stop this bad practice --- by looking at "oxygen" nobody knows what it is.

**Pull request merged**
