### PR TITLE
external-dns: update external-dns to v0.4.4

### PR DESCRIPTION
**Pull request by linki**
update external-dns to v0.4.4

### CODE REVIEW

**Comment by hjacobs** [comment]
@linki link to release notes and the "why" would always be nice (in this case it's an important bug fix AFAIK).

**Comment by hjacobs** [comment]
This version bump includes a bugfix for FQDN template: https://github.com/kubernetes-incubator/external-dns/releases/tag/v0.4.3

**Comment by hjacobs** [comment]
Updated to fresh release: https://github.com/kubernetes-incubator/external-dns/releases/tag/v0.4.4

**Comment by linki** [comment]
Still failing. I rebased on 1.7 as we'll update soon and it's a working version.

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
