### PR TITLE
Update to external-dns v0.12.2

### PR DESCRIPTION
**Pull request by mikkeloscar**
https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.12.2

### CODE REVIEW

**Comment by demonCoder95** [comment]
Summary of important changes `v0.12.0 -> 0.12.2`:
1. Support for migration to TXT records [see change here](https://github.com/kubernetes-sigs/external-dns/commit/50f196c0db280de7a9b55a8f7fd6b0a607ac5472) _SEEMS RELEVANT_
2. IP addresses as strings are "less" than domain names, update to `endpoint.go` logic. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/0c8f6a69bda2034ef00e1766dd0a9058dfd03dd6) _SEEMS RELEVANT_.
3. Supporting proxying wildcard domains for `cloudflare` provider.[see change here](https://github.com/kubernetes-sigs/external-dns/commit/b21d11be92a56f4e742ce187ba6645a1e9d96191)  _maybe not relevant_

Looking at changes `v0.11.0 -> v0.12.0` now.

**Comment by demonCoder95** [comment]
Summary of important changes `v0.11.0 -> v0.12.0`. I list all potentially breaking changes here just so we can understand the version skew. Ignoring minor docs/CI patches done to the upstream:
1. Addition of `Gateway API` support for sources. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/db8435d7ca8b099d1350865a3aaed08831a7a2cc)  _maybe not relevant_
2. Addition of `nodes` as sources. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/9daca3e06034c3231e4d9f9eb559ae747e82a7ed) _maybe not relevant_
3. Upgrading the `infoblox` provider go-client to `v2`. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/f890d882e206240bdf34700a6c77775c424b5c11) _maybe not relevant_
4. Moving the `bluecat` provider to a new pkg [see change here](https://github.com/kubernetes-sigs/external-dns/commit/83f062fbf77634fa86f201e07c1557d5aa639bdc). _maybe not relevant_

Given that we use the `aws` provider with sources `service`, `ingress` and `skipper-routegroup`[see here](https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/cluster/manifests/external-dns/deployment.yaml#L39)  

**_None of the major changes in this version bump are relevant to our implementation._**

Looking at `v0.10.0 -> v0.11.0` now.

**Comment by demonCoder95** [comment]
Summary of important changes `v0.10.0 -> v0.11.0`. Major changes that seem relevant to our implementation:
1. Update `service` source to not merge endpoints with different set identifier. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/c1af8a40ecc1ce327d0015c62057e63cafffae04)
2. Update change submitting logic for the `aws` provider to remove `record` and `zone` as parameters. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/1aef05c8e511ed37ab0bafaff245d4ab32f46965)
3. Add `label` based filtering for `ingress` and `service` sources. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/d91b7e6b8fc92d0a35c30a4cfc00ee5de6db5993).
4. Add `external_dns_controller_verified_records` as a new Gauge type metrics to prometheus. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/39d5b39e18badcb52e05262a7452bae1863fd6c2).
5. Add `external_dns_registry_a_records ` and `external_dns_source_a_records ` as new Gauge type metrics. This is to be able to track the progress of A record synchronisation between registry and source. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/19d9bc8ef99b8cb083f0485df816db46dd68e5fc).
6. Add canonical hosted zone for cloudfront to the `aws` provider. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/93b3cf95b63c9f41bebddb0f9e35420eb904dc36).
7. Add controller context to the `InformerFactory` method for creating `ingress` and `service` sources so it can stop when the controller stops. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/4f41229820a40bdeb5f180799f85415aad0e4bcc).
8. Update `aws` tutorial documentation to add information about [API rate-limiting](https://github.com/kubernetes-sigs/external-dns/commit/45886608db4e85993e6bf7e15ba35d96e0489890) and [randomising startup](https://github.com/kubernetes-sigs/external-dns/commit/61e3948981e5579309e1ec186dcb2e048012675a) of `external-dns` pods.

There are other updates to different providers that we are not using, and updates to CI as well as Helm charts. Lots of relevant changes in this version bump.

Also, the Kubernetes version compatibility matrix [here](https://github.com/kubernetes-sigs/external-dns#kubernetes-version-compatibility) lists that the minimum version supported for `k8s 1.22` is `v0.10.0`.

**Comment by demonCoder95** [comment]
Summary of important changes `v0.9.0 -> v0.10.0`. Major changes that are relevant to our implementation:
1. Update `ingress` source to `v1` for `external-dns`. [see change here](https://github.com/kubernetes-sigs/external-dns/commit/0e27f41fa0457e105b591e76c0d6f57bcb23bc74)

The rest seems irrelevant changes. Updating ingress RBAC from `extensions` to `networking` is already part of this PR, so I think we cover that.

**Comment by demonCoder95** [comment]
Other major dependency version bumps in the commit history (from `v0.9.0 -> v0.12.2`) include:
1. Bump `go` to `1.18` [see change here](https://github.com/kubernetes-sigs/external-dns/commit/316345731c34ab88521767731ec33f8664889af2)
2. Bump `alpine` to `3.15` [see change here](https://github.com/kubernetes-sigs/external-dns/commit/2f10b891855cb3abcf75cc2bcb2fda50d9aa7c90)
3. Bump `aws-sdk-go` to `1.42.52` [see change here](https://github.com/kubernetes-sigs/external-dns/commit/718ba054d0cee15e166994cb20c95b400c3d58fe)
4. Bump `client-go` to `0.22.2` [see change here](https://github.com/kubernetes-sigs/external-dns/commit/6aeee9e21180338a6829a1ab8745033d29274ea8).

I believe these are the major version bumps that are most relevant to our implementation.

**Comment by demonCoder95** [comment]
If we think there's nothing too serious here that we need to address, then we can start to roll this upgrade out like we did for the `vertical-pod-autoscaler` using a config-item [here](https://github.com/zalando-incubator/kubernetes-on-aws/pull/5361). 

This will allow us to monitor issues (if any) with the `external-dns` upgrade and roll-back to the legacy version if needed. Feel free to review the changes I summarised and let me know if we can start rolling out the upgrade 🙂 

cc @szuecs @mikkeloscar

**Comment by szuecs** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
