### PR TITLE
fix traffic switching

### PR DESCRIPTION
**Pull request by szuecs**
fix blue green deployments creted 500s caused by a skipper route matching issue

### CODE REVIEW

**Comment by hjacobs** [comment]
Can you say some more words about the issue and how it was resolved?

**Comment by szuecs** [comment]
@hjacobs basically we check now, that if a decision header is set, we do not match the lb_group predicate again, which could trigger an infinte loop.

Once we have a decision of the loadbalancer group made by one decision route, we made it impossible to match the decision route again, which triggered the infinite loop. Infinite loop was triggered in ~10% of the calls, dependent on the Traffic() predicate setting.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
