### PR TITLE
bump version not ignore errors on findLoadbalancers

### PR DESCRIPTION
**Pull request by szuecs**
Do not recreate ALBs if we are rate limited. Treat rate limits as error.

### CODE REVIEW

**Comment by hjacobs** [comment]
Please also update the version labels.

**Comment by hjacobs** [comment]
Please link the relevant release notes / changelog: https://github.com/zalando-incubator/kube-ingress-aws-controller/releases

(and create the release notes for ingress controller first)

**Comment by szuecs** [comment]
Here the link to the release:
https://github.com/zalando-incubator/kube-ingress-aws-controller/releases/tag/v0.2.1

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Damn, we did not update the version labels...

**Pull request merged**
