### PR TITLE
Modernize instance types in e2e

### PR DESCRIPTION
**Pull request by mikkeloscar**
Use more modern instance types during e2e.

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
@mikkeloscar I hope we don't have to wait long for m7i nodes... x7i seems to be not too much available in our region

**Comment by mikkeloscar** [comment]
Yes, I didn't choose x7i as I don't know how available they are.

**Pull request merged**
