### PR TITLE
[2017-06-22] promote dev to alpha

### PR DESCRIPTION
**Pull request by linki**
promote dev to alpha

Changes
* external-dns v0.4.0-alpha.0
* kube2iam v0.6.2
* Update ingress controller (#463)
* Kubernetes v1.6.6 (#459)
* Update ZMON (#453, #468)
* Added deployment role and KMS key ( #469 ) 
* Introduce kube-node-ready ( #470 )
* Make instance type for master nodes configurable ( #473 )

### CODE REVIEW

**Comment by mikkeloscar** [comment]
We need to find a workaround for the 3rd AZ before we merge this.

**Comment by mikkeloscar** [comment]
@linki I updated this with the latest features from dev.

**Comment by Raffo** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
