### PR TITLE
add "anonymized" cheat sheet

### PR DESCRIPTION
**Pull request by hjacobs**
Add "anonymized" cheat sheet (converted with internal `kubernetes-cheat-sheet-to-example.sh` script) to serve as an example/template for others to create their own Kubernetes cheat sheets.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Would it make sense to also remove **z** from `zkubectl`?

**Comment by hjacobs** [comment]
@mikkeloscar the `list` and `login` commands won't work and I don't want to redesign the whole sheet for public use (also the architecture image with Skipper+Ingress is obviously specific to our setup) --- I consider this more a template for other people (to adapt for their company) and not a cheat sheet to use "out of the box".

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
