### PR TITLE
Update `kubernetes-log-watcher`

### PR DESCRIPTION
**Pull request by anton-ryzhov**
To use updated configuration https://github.com/zalando-incubator/kubernetes-log-watcher/pull/106

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by femueller** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
Also updated `logging_agent_version`

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
