### PR TITLE
Upgrade zmon components

### PR DESCRIPTION
**Pull request by mohabusama**
Upgrade zmon components to latest

Changes:

*zmon-worker*

- Fix OpenTracing context propagation from scheduler
- Fix negative average metrics

*zmon-scheduler*

- Add scheduler with OpenTracing support

*zmon-aws-agent*

- Fix public ip exception in postgres discovery

*zmon-agent*

- Fix failed add_entity

### CODE REVIEW

**Comment by mohabusama** [comment]
@linki is it failing due to the changes?

**Comment by mikkeloscar** [comment]
@mohabusama this was due to our e2e setup being somewhat broken. This is now fixed.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mohabusama** [comment]
👍

**Pull request merged**
