### PR TITLE
skipper: allow use of endpointslices without routesrv

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Followup on #6482

### CODE REVIEW

**Comment by szuecs** [comment]
Why?

**Comment by AlexanderYastrebov** [comment]
To avoid local `make test` passing without 100% coverage which requires one to amend pull request later after pipeline fails.

**Comment by AlexanderYastrebov** [comment]
We have all other options in parallel such that we can disable routesrv and let skipper talk to k8s

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
