### PR TITLE
Add parameter to whitelist additional labels in ksm for pods and ingresses #5832

### PR DESCRIPTION
**Pull request by kostz**
part of https://github.com/zalando-incubator/kubernetes-on-aws/issues/5831

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by kostz** [comment]
👍

**Comment by demonCoder95** [comment]
👍

**Comment by mikkeloscar** [comment]
@kostz needs rebase now

**Comment by mikkeloscar** [comment]
:+1:

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
