### PR TITLE
Fixed typo in apiGroups in zmon rbac config

### PR DESCRIPTION
**Pull request by arjunrn**
Fix typo in name

Signed-off-by: Arjun Naik <arjun.rn@gmail.com>

### CODE REVIEW

**Comment by arjunrn** [comment]
@mikkeloscar Can you approve this?

**Comment by arjunrn** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
When we skip e2e tests :D

**Comment by arjunrn** [comment]
> When we skip e2e tests :D

Would it have been caught by the e2e tests though because none of the tests check for rbac roles.

**Pull request merged**
