### PR TITLE
Parameterizing AutoscalingGroup->SpotAllocationStrategy

### PR DESCRIPTION
**Pull request by muaazsaleem**
Making AllocationStrategy configurable for Nodepool ASGs so applications
so disruption tolerant workloads can potentially save cost.

Signed-off-by: Muaaz Saleem <muhammad.muaaz.saleem@zalando.de>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by arjunrn** [comment]
Are the config items from the cluster copied over into the nodepool config items?

**Comment by mikkeloscar** [comment]
> Are the config items from the cluster copied over into the nodepool config items?

Yup, we use this for a few cases already like `cpu_manager_policy` and `pod_max_pids`

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
