### PR TITLE
bump log-watcher-version to 0.36

### PR DESCRIPTION
**Pull request by pheanex**
* [Increase max line length to 49900 for scalyr agent](https://github.com/zalando-incubator/kubernetes-log-watcher/pull/95)
* [Add option to enable profiling](https://github.com/zalando-incubator/kubernetes-log-watcher/pull/96)
@zalando-incubator/team-kubernetes-log-watcher please review

### CODE REVIEW

**Comment by pheanex** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
Don't you want to use 0.36 after https://github.com/zalando-incubator/kubernetes-log-watcher/pull/96 be merged?

**Comment by pheanex** [comment]
Yes, but did not know how long it takes to review :smile:

**Comment by pheanex** [comment]
:+1:

**Comment by pheanex** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
