### PR TITLE
vpa is enabled by default no need to guard it anymore

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Should we also remove the configuration from here? https://github.com/zalando-incubator/kubernetes-on-aws/blob/3d1f5e816c740906edfc692e15aa1d0bfbd45ebb/cluster/config-defaults.yaml#L119

**Comment by szuecs** [comment]
done

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
