### PR TITLE
add opentracing tags

### PR DESCRIPTION
**Pull request by zeitlinger**
- added `account`, `application`, and `artifact` global tags
- eventually, `cluster` global tag will be removed, as it's the same as `cluster`, but not in this PR

### CODE REVIEW

**Comment by szuecs** [comment]
no changes will be rolled out until BF

**Comment by szuecs** [comment]
this PR will break the complete deployment

**Comment by szuecs** [comment]
Thanks @zeitlinger PR looks good to me, we will postpone the rollout until after BF.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by zeitlinger** [comment]
I did a mistake and created #2732 to fix it.

**Pull request merged**
