### PR TITLE
dnsmasq: fix configuration to ignore resolv.conf

### PR DESCRIPTION
**Pull request by aermakov-zalando**
This fixes resolution of in-cluster names.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
Can you explain the background? PRs without context don't make sense to me.

**Comment by szuecs** [comment]
@hjacobs it used the wrong configuration. Basically it used the configuration from the node itself, which can't resolve .cluster.local.

**Pull request merged**
