### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by gargravarr**
* **Update zmon-worker**
   <sup>Merge pull request #1199 from zalando-incubator/update-zmon-worker</sup>
* **Update hyperkube to 1.10.5**
   <sup>Merge pull request #1197 from zalando-incubator/use-gcr-image</sup>
* **Enable CustomResourceSubresources=true featuregate**
   <sup>Merge pull request #1196 from zalando-incubator/crd-subresource</sup>
* **Apply security best practices (ro rootfs, runAsUser)**
   <sup>Merge pull request #1161 from zalando-incubator/security-context-readonly-rootfs</sup>

### CODE REVIEW

**Comment by gargravarr** [comment]
:+1:

**Comment by linki** [comment]
Any thoughts on promoting `CustomResourceSubresources=true` to alpha that quickly? Do you expect any issues @mikkeloscar?

**Comment by mikkeloscar** [comment]
@linki from my PoV it's fine. I don't see that it should have an impact as long as we don't start to depend on this API in the current state. But having it available is not a problem IMO.

**Comment by mikkeloscar** [comment]
Let's schedule roll-out for Wednesday 2018-06-27

**Comment by linki** [comment]
👍

**Pull request merged**
