### PR TITLE
Adjust resource requests for logging

### PR DESCRIPTION
**Pull request by mohabusama**
- Update log-watcher and scalyr-agent

Signed-off-by: Mohab Usama <mohab.abdelhameed@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👎

**Comment by aermakov-zalando** [comment]
Blocking until we switch to daemonset scheduling with the normal scheduler. This will just cause half of the nodes to end up with no logging whatsoever.

**Comment by aermakov-zalando** [comment]
Alternatively, we could merge it in 3 PRs by changing the update strategy to `OnDelete`, merging memory changes, rolling all the nodes and then changing the strategy back, but this will be incredibly annoying. We could do it if it's necessary for Black Friday, of course.

**Comment by szuecs** [comment]
@aermakov-zalando do we have an issue for this?
And does @mohabusama understand what has to be done?

**Comment by aermakov-zalando** [comment]
@szuecs We do. @mohabusama do you want this to be done before BF? If yes, I can help you with splitting it around, otherwise I'd wait until we solve the update issues.

**Comment by mohabusama** [comment]
@aermakov-zalando No, not needed before BF. It was mainly added to address the resource request vs limit situation.

**Comment by szuecs** [comment]
@mohabusama @aermakov-zalando I guess we can merge this, not?

**Comment by aermakov-zalando** [comment]
@szuecs not yet, we still haven't enabled the feature flag for proper DS scheduling.

**Comment by szuecs** [comment]
Close in favor of #1680

**Pull request closed without merging**
