### PR TITLE
Enable previously disabled e2e tests for authz

### PR DESCRIPTION
**Pull request by mikkeloscar**
Enable previously disabled authz related e2e tests now that it should be working via #8571

### CODE REVIEW

**Comment by demonCoder95** [comment]
For EKS, these need to remain skipped, since the tests have been rewritten to use client-go, specifically for an EKS environment.

For the `dev` branch, we can unskip them and the pipeline should succeed, as both new and old tests should be successful for non-EKS setup. 

However, we can't then merge this change in EKS for the reasons mentioned above, the pipeline would fail, as the existing RBAC test suite is not compatible with the EKS apiserver.

**Comment by demonCoder95** [comment]
I notice the secrets reading RBAC from the new suite is also failing still. I've identified the issue with the RBAC permissions of the role-sync-controller. I'll use this PR to test the change.

**Comment by demonCoder95** [comment]
Cherry-picked the fix in #8608 to test the fix.

**Comment by demonCoder95** [comment]
This should now be fixed. 

I updated the comment on the TODO because we cannot unskip those tests as they break fundamentally. Once we finish rewriting the RBAC tests and remove the existing tests from the setup, we can remove this line.

**Comment by demonCoder95** [comment]
👍

**Comment by demonCoder95** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
