### PR TITLE
Move infrastructure-secrets to the internal repo

### PR DESCRIPTION
**Pull request by aermakov-zalando**
We don't use any of these in the public manifests anymore, so this can be moved.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
Will cleanup the cluster template in a separate PR to not break the tests.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
