### PR TITLE
allow to configure whther to run node-problem-detector

### PR DESCRIPTION
**Pull request by linki**
after discussion with @aermakov-zalando 
* reset the default resource requirements for cadvisor
* make problem detector component optional

### CODE REVIEW

**Comment by linki** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Rebased because CDP couldn't check out the branch

**Comment by jrake-revelant** [comment]
👍

**Pull request merged**
