### PR TITLE
Configure dependabot for skipper

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
Dependabot supports Helm charts which use similar template language as CLM. This is an experiment to test whether dependabot can update images in skipper templates.

### CODE REVIEW

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
It works and recognizes images in manifests but fails to authenticate to  container-registry.zalando.net

Screenshot from 2024-02-20 16-05-47

Screenshot from 2024-02-20 19-22-32

**Comment by AlexanderYastrebov** [comment]
Created internal ticket to authenticate Github Dependabot in container-registry.zalando.net

**Pull request merged**
