### PR TITLE
Collaborator role: fix daemonsets

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* Fix apiGroups, daemonsets don't live in core.
* Remove the restriction on the resource name, no point in doing it.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Comment by szuecs** [comment]
This would allow everyone to deploy daemonsets, not?

**Comment by aermakov-zalando** [comment]
No, only those with the collaborator roles.

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
