### PR TITLE
application opentracing tag

### PR DESCRIPTION
**Pull request by zeitlinger**
upgrade admission-controller to add application opentracing tag

### CODE REVIEW

**Comment by zeitlinger** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by zeitlinger** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
@zeitlinger you are not allowed to count for a +1, it's only a miss leading zappr message that it counts you in the first place

**Comment by zeitlinger** [comment]
@szuecs deleted the messages

**Pull request merged**
