### PR TITLE
Drop kube-dns-metrics

### PR DESCRIPTION
**Pull request by mikkeloscar**
We no longer rely on the metrics provided by this so let's drop it.

We have metrics from CoreDNS and dnsmasq which covers what we need.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
@mikkeloscar do we need a change in e2e test and remove from zmon?

**Comment by mikkeloscar** [comment]
@szuecs Not e2e, I think the failure we see is not related. For zmon and others I have created an internal ticket to track the cleanup.

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
