### PR TITLE
Testing/authorization tests

### PR DESCRIPTION
**Pull request by aryszka**
- [x] improve readability/maintainability of existing tests
- [x] define categories for grouping the authz related tests
- [x] find and implement the set of tests to have a safer coverage of authz

### CODE REVIEW

**Comment by szuecs** [comment]
Please drop label as soon we can review, thanks

**Comment by mikkeloscar** [comment]
@aryszka Cool! Looks good to me, much simpler to read now.

Needs a rebase since: https://github.com/zalando-incubator/kubernetes-on-aws/commit/221504551147ec69640ad8437f89bd1037b57b69#diff-8b697bd72688e03ea31d110d13bdef31

**Comment by aryszka** [comment]
thanks for the review, rebased it.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
