### PR TITLE
MID-2409 remove fabric ClusterRoles, these are no longer needed

### PR DESCRIPTION
**Pull request by cjbooms**
On suggest from @mikkeloscar Team Fabric have defined the required `ClusterRole`'s  in each of their operator repositories, along with a `ClusterRoleBinding` that binds these `ClusterRole`'s to the `ServiceAccount` used by their `StatefulSet` `metacontroller`

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by arjunrn** [comment]
@mikkeloscar we need to add these to the delete list right?

**Comment by mikkeloscar** [comment]
They are named the same as what we automatically create from the admission-controller, so they will just be overwritten by that process.

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
