### PR TITLE
Update Kubernetes to v1.23

### PR DESCRIPTION
**Pull request by katyanna**
v1.23: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md
Announcement: https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/

### CODE REVIEW

**Comment by demonCoder95** [comment]
Rebased on `dev`, e2e is failing, will try to fix that next.

**Comment by mikkeloscar** [comment]
@demonCoder95 I think this is not correctly rebased as it contains commits already in `dev` :thinking:

**Comment by demonCoder95** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by katyanna** [comment]
👍

**Pull request merged**
