### PR TITLE
Update image policy hook with simulate and metrics

### PR DESCRIPTION
**Pull request by linki**
Updates imagePolicyWebhook with the `--simulate` feature and a `/metrics` endpoint.

### CODE REVIEW

**Comment by linki** [comment]
The test that fails is the test that tests the imagePolicyWebhook. It fails because it runs in `simulation` mode and thus doesn't reject the image. @mikkeloscar what do you think on how to proceed? An additional config item seems overkill.

**Comment by linki** [comment]
Temporarily disable image-policy check: https://github.bus.zalan.do/teapot/kubernetes-e2e-tests/pull/17

Revert this PR once simulation mode is disabled.

**Comment by Raffo** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
