### PR TITLE
Dev to alpha

### PR DESCRIPTION
**Pull request by hjacobs**
* use real initContainers (1.6)
* Skipper: use affinity to not schedule on master nodes

### CODE REVIEW

**Comment by hjacobs** [comment]
e2e failed:

```
FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "zmon-aws-agent" with ErrImagePull: "rpc error: code = 2 desc = unauthorized: authentication required"

**Comment by szuecs** [comment]
rerun seemed to help

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
