### PR TITLE
Bumps instana version to 11

### PR DESCRIPTION
**Pull request by elgris**
fixes the problem with non-autostarting agents

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Test won't run for forks. I think it's ok to merge this without running e2e.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by elgris** [comment]
@mikkeloscar if I have had access to base repo, I would send a PR directly from there :)

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
