### PR TITLE
bump secretary to v0.3.1

### PR DESCRIPTION
**Pull request by linki**
bump secretary to v0.3.1

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
Why are we updating secretary?

**Comment by hjacobs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
This added retry strategy to the get instance identity document call. This ensures that secretary will retry the call in case it comes up a bit before kube2iam, rather than failing and waiting for 10m before it recovers.

**Pull request merged**
