### PR TITLE
stactset-e2e: control wait timeout with flags

### PR DESCRIPTION
**Pull request by MustafaSaber**
Add environment variables to the script with old default values and pass them from CI.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
seems not to work to increase timeouts

**Comment by MustafaSaber** [comment]
yeah doesn't seem to work, it's just some guts that it still some timeout. I will try to invest more once I have time.

**Pull request closed without merging**
