### PR TITLE
Kubernetes v1.13

### PR DESCRIPTION
**Pull request by mikkeloscar**
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#v1135

### CODE REVIEW

**Comment by mikkeloscar** [comment]
statefulset tests are failing because of https://github.com/kubernetes/kubernetes/issues/73507 which is only in v1.14

**Comment by mikkeloscar** [comment]
Switched e2e tests to use `CockroachDB` test instead of the broken `zookeeper` based test.

**Comment by jrake-revelant** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
