### PR TITLE
Apply security best practices (ro rootfs, runAsUser)

### PR DESCRIPTION
**Pull request by hjacobs**
Apply security best practices such as read-only container file system and running as non-root. Some relevant links:

* https://kubernetes.io/blog/2016/08/security-best-practices-kubernetes-deployment/
* https://github.com/Shopify/kubeaudit

I only applied it for some manifests to get started.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by linki** [comment]
👍

**Comment by aermakov-zalando** [comment]
Did you test that the dashboard works?

**Comment by hjacobs** [comment]
@aermakov-zalando actually no, but at least the container starts. Don't we have it in e2e tests? :smirk:

**Comment by aermakov-zalando** [comment]
Unfortunately we don't. Would you mind checking?

**Comment by hjacobs** [comment]
I tested the Kubernetes Dashboard: it works fine with the changes (uid, read-only filesystem).

**Pull request merged**
