### PR TITLE
enable zmon from root account to query AWS metrics in other accounts

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Please build it using data we already have. Setting it manually is annoying.

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
One cluster should be successfully created before merge

**Comment by szuecs** [comment]
:+1:

**Comment by dionb** [comment]
:+1:

**Pull request merged**
