### PR TITLE
Missing resources added

### PR DESCRIPTION
**Pull request by roflc0pter**
Context: https://github.com/zalando-incubator/kubernetes-on-aws/pull/2202
Missing resources added for: https://github.bus.zalan.do/pitchfork/developer-console/issues/528#issuecomment-1435718

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@roflc0pter please signoff your commit :)

**Comment by roflc0pter** [comment]
@mikkeloscar done :)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by njuettner** [comment]
:+1:

**Pull request merged**
