### PR TITLE
Update the CSI manifests to the latest state

### PR DESCRIPTION
**Pull request by linki**
Updates the CSI Deployment files to the latest versions and configuration.

Manifests are based on the official deployment manifests in: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/deploy/kubernetes

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by demonCoder95** [comment]
👍

**Comment by demonCoder95** [comment]
Where do we get these manifests from? Is there some upstream repository we match to?

**Comment by linki** [comment]
Yes, it's from upstream. I'll leave a link in the top for reference.

**Pull request merged**
