### PR TITLE
Update kubernetes-log-watcher to 0.30

### PR DESCRIPTION
**Pull request by pheanex**
Change includes:
* Rename logfiles before sending them to Scalyr (See 'rename_logfile' in https://www.scalyr.com/help/scalyr-agent)

### CODE REVIEW

**Comment by pheanex** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@pheanex what is the new file naming pattern? :)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
@mikkeloscar https://github.com/zalando-incubator/kubernetes-log-watcher/pull/88

**Comment by pheanex** [comment]
Basically what we are doing here is to change the log-file-name (that we ship to scaler) to include application, component and version labels from kubernetes in order to do better cost attribution.
The pattern is "?application=\<application>&component=\<component>&version=\<version>"
For more details and background see the linked PullRequest from Anton

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
