### PR TITLE
Shared secret is now in a CSV file

### PR DESCRIPTION
**Pull request by Raffo**
Webhook version is clearly a placeholder as this depends on other PRs. 
Implements tokens from a file in CSV format.

### CODE REVIEW

**Comment by Raffo** [comment]
Sorry, terrible title originally.

**Comment by szuecs** [comment]
@Raffo

**Comment by Raffo** [comment]
LGTM

**Comment by Raffo** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
