### PR TITLE
stackset-e2e: Don't run in parallel

### PR DESCRIPTION
**Pull request by mikkeloscar**
Don't run stackset e2e in parallel to see if it makes a difference on the flakyness.

If this works it's just a band-aid on the problem.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
This increases the time it takes for running the stackset e2e from around 15 min. to 45 min...

**Comment by rodrigodelmonte** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
Merging this is a simple mitigation which is better than nothing.

**Pull request merged**
