### PR TITLE
Update dashboard version

### LINKED ISSUE #161: Update dashboard version to 1.5.0
Some nice features we definitely want (e.g. displaying more information, HPA support):
https://github.com/kubernetes/dashboard/releases/tag/v1.5.0

### PR DESCRIPTION
**Pull request by Raffo**
Closes #161

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
Update `version` labels? (leads to problems...)

**Comment by hjacobs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
