### PR TITLE
feat:mount default filters ConfigMap for Skipper (#1959)

### LINKED ISSUE #1959: ConfigMap for Skipper default filters
* Specify the ConfigMap resource
* Mount (optional) ConfigMap to Skipper's file system

Related to https://github.com/zalando/skipper/pull/983.

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Closes #1959 

Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>

### CODE REVIEW

**Review by tkrop — CHANGES_REQUESTED** [review]
The configmap for `skipper-default-filters` is actually already part of #1956.

**Review by tkrop — APPROVED** [review]

**Comment by tkrop** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
