### PR TITLE
check local tokeninfo is ready on startup

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by ruiaraujo** [comment]
what happens if local token info fails to starts?

**Comment by szuecs** [comment]
@ruiaraujo skipper will not start the Listener, such that ALB/NLB target group will not see it as healthy and kubernetes does not see this as ready, too. 
https://github.com/zalando/skipper/pull/1292 is the change

**Comment by ruiaraujo** [comment]
Yes, but could a permanent failure of the side car prevent the ingress from scaling up?

**Comment by szuecs** [comment]
Answered internally

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
