### PR TITLE
kubelet: drop readOnlyPort

### PR DESCRIPTION
**Pull request by aermakov-zalando**
We forgot to drop this, and it's not used anymore.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Could we include this in v1.16 rollout? No need to roll the nodes just for this IMO.

**Comment by aermakov-zalando** [comment]
Sure, but we have an AMI update coming soon anyway, no? For 1.16 we still need to fix CA.

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
