### PR TITLE
Add scalyr read key to zmon-worker manifest

### PR DESCRIPTION
**Pull request by mohabusama**
Changes:

- Update ``zmon-worker`` manifest to include ``SCALYR_READ_KEY`` to allow zmon checks read access from the cluster scalyr account.

Note: Depends on ``"{{ .ConfigItems.scalyr_read_key }}"``

### CODE REVIEW

**Comment by hjacobs** [comment]
We should update our internal Cluster Registry before merging this.

**Comment by mikkeloscar** [comment]
I'll add the keys to the registry.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
