### PR TITLE
Update to 1.15.9

### PR DESCRIPTION
**Pull request by aermakov-zalando**
[Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#v1159).

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👎

**Comment by aermakov-zalando** [comment]
Includes #2889.

**Comment by arjunrn** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
