### PR TITLE
[db-alpha] Required Next: Promote dev to db-alpha

### PR DESCRIPTION
**Pull request by linki**
### Note this must be merged separately/before any other merges to db-alpha

Notable changes:
* Add support for our own etcd proxy
* Prepare kube-proxy daemonset rollout
* Prepare flannel daemonset rollout
* Add PodCIDR Controller for flannel migration
* Use latest version of ingress controller
* Remove ClusterID tag frome CF
* Expire old etcd backups
* Upgrade zmon-agent to include deep-link (clean tag)

### CODE REVIEW

**Comment by szuecs** [comment]
Anything which prevents us from deploying?
Do we have already a timeframe discussed for this deployment?

**Comment by linki** [comment]
@szuecs we could wait until we have the new update strategy and postgres-operator. Then this will be just as any other update.

**Comment by linki** [comment]
Mergeable when ACID deployed the postgres-operator with the improved update strategy.

**Comment by linki** [comment]
~~TODO: cherry-pick docker downgrade commit: f982c4a55e28fe3fc861ff5cd071c195507cab3d~~ 👍

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
Homage to @Raffo 🎉 

w7c6bbj

**Pull request merged**
