### PR TITLE
Update Prometheus to 2.13.1

### PR DESCRIPTION
**Pull request by mikkeloscar**
Lots of changes and bug fixes since 2.10.0

* https://github.com/prometheus/prometheus/releases/tag/v2.13.1
* https://github.com/prometheus/prometheus/releases/tag/v2.13.0
* https://github.com/prometheus/prometheus/releases/tag/v2.12.0
* https://github.com/prometheus/prometheus/releases/tag/v2.11.1
* https://github.com/prometheus/prometheus/releases/tag/v2.11.0

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
This also enables scraping of etcd nodes prometheus-exporter endpoint.

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
