### PR TITLE
Update to Kubernetes v1.13

### PR DESCRIPTION
**Pull request by mikkeloscar**
**JUST FOR TESTING FOR NOW**

Needs to be against `dev` once `v1.12` is out everywhere.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#v1132

### CODE REVIEW

**Comment by mikkeloscar** [comment]
This is failing at least because of: https://github.com/kubernetes/kubernetes/issues/73044

PR: https://github.com/kubernetes/kubernetes/pull/73046

**Comment by mikkeloscar** [comment]
And another bug in the e2e tests: https://github.com/kubernetes/kubernetes/issues/73184

**Comment by jrake-revelant** [comment]
Should we retry with v1.13.4?

**Comment by aermakov-zalando** [comment]
Is GKE (the only real Kubernetes deployment apparently) even running 1.12?

**Comment by mikkeloscar** [comment]
@aermakov-zalando GKE has 1.12.5 now fwiw (but not the default suggested)

image

**Comment by mikkeloscar** [comment]
Closing in favor of #1945 which is targeting `dev`

**Pull request closed without merging**
