### PR TITLE
Remove zmon-aws-agent VPA

### PR DESCRIPTION
**Pull request by aermakov-zalando**
`zmon-aws-agent` doesn't really work correctly with the VPA because instead of running directly it runs under `bash`->`timeout`, and signals/exit statuses aren't propagated correctly.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
Can you create an issue for them to change their startup script, please?

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
@szuecs Sure!

**Pull request merged**
