### PR TITLE
kube2iam v0.4.1

### PR DESCRIPTION
**Pull request by hjacobs**
Latest release of kube2iam: https://github.com/jtblin/kube2iam/compare/0.3.0...0.4.1

There are sadly no official release notes for newer releases than 0.3.0: https://github.com/jtblin/kube2iam/issues/64

### CODE REVIEW

**Comment by hjacobs** [comment]
e2e test fails with:

```
time="2017-04-21T18:16:13Z" level=fatal msg="readdirent: not a directory
cannot read directory
github.bus.zalan.do/teapot/cluster-lifecycle-manager/provisioner.(*clusterpyProvisioner).Apply
```

I guess the CLM chokes on `deletions.yaml` and needs to be updated in e2e?

**Comment by mikkeloscar** [comment]
I actually think it's the `scalyr_read_key` config item which has to be added to the e2e test. The error message is a bit misleading for some reason...

**Comment by mikkeloscar** [comment]
@hjacobs created a PR in GHE.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by jtblin** [comment]
Added release notes to kube2iam :)

[0.5.0](https://github.com/jtblin/kube2iam/releases/tag/0.5.0) is out btw.

**Pull request merged**
