### PR TITLE
use optional config map for WORKER_PLUGIN_HTTP_OAUTH2_TOKEN

### PR DESCRIPTION
**Pull request by vetinari**
see also https://github.com/zalando-incubator/kubernetes-on-aws/pull/1726

Signed-off-by: Hanno Hecker <hanno@zalando.de>

### CODE REVIEW

**Comment by vetinari** [comment]
as reference: we need to set the config map in a cluster where it's used like 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: zmon-worker-optional-config
  namespace: visibility
data:
  WORKER_PLUGIN_HTTP_OAUTH2_TOKENS: "refname=scope1,scope2;refname2=scope3,scope2"

```

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
@vetinari do you forgot to have the configmap in your PR or is the configmap delivered with a different deployment strategy?

**Comment by vetinari** [comment]
We'll deploy the configMap on demand, otherwise it's default version would be overwrite our by your deployments

**Pull request merged**
