### PR TITLE
Bump of mem limits for apiserver

### PR DESCRIPTION
**Pull request by Raffo**
This is needed not to get them OOMkilled, this will probably just give us some time to breathe before we have a better solution.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
We also need to bump the memory for controller manager, it gets OOMKilled too...

```
kube-controller-manager-ip-172-31-2-248.eu-central-1.compute.internal   0/1       CrashLoopBackOff   73         1d
```

```
$ zkubectl describe pod kube-controller-manager-ip-172-31-2-248.eu-central-1.compute.internal -n kube-system
Name:		kube-controller-manager-ip-172-31-2-248.eu-central-1.compute.internal
Namespace:	kube-system
Node:		ip-172-31-2-248.eu-central-1.compute.internal/172.31.2.248
Start Time:	Fri, 27 Jan 2017 10:34:22 +0100
Labels:		application=kube-controller-manager
		version=v1.5.2_coreos.0
Status:		Running
IP:		172.31.2.248
Controllers:	<none>
Containers:
  kube-controller-manager:
    Container ID:	docker://23bc9c51b1cf310c0164b647f057f66e483f286121026c19bdc1ae9a40f62f30
    Image:		registry.opensource.zalan.do/teapot/hyperkube:v1.5.2_coreos.0
    Image ID:		docker-pullable://registry.opensource.zalan.do/teapot/hyperkube@sha256:798519e5ea6f676222580ed032b33fd3cc8b616a9419b2f2434f3bddff3db7e7
    Port:		
    Command:
      /hyperkube
      controller-manager
      --master=http://127.0.0.1:8080
      --leader-elect=true
      --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
      --root-ca-file=/etc/kubernetes/ssl/ca.pem
      --cloud-provider=aws
      --feature-gates=AllAlpha=true
    Limits:
      cpu:	200m
      memory:	200Mi
    Requests:
      cpu:		100m
      memory:		100Mi
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		OOMKilled
      Exit Code:	137
      Started:		Sat, 28 Jan 2017 14:50:48 +0100
      Finished:		Sat, 28 Jan 2017 14:52:48 +0100
    Ready:		False
    Restart Count:	73
    Liveness:		http-get http://127.0.0.1:10252/healthz delay=15s timeout=15s period=10s #success=1 #failure=3
    Volume Mounts:
      /etc/kubernetes/ssl from ssl-certs-kubernetes (ro)
      /etc/ssl/certs from ssl-certs-host (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  ssl-certs-kubernetes:
    Type:	HostPath (bare host directory volume)
    Path:	/etc/kubernetes/ssl
  ssl-certs-host:
    Type:	HostPath (bare host directory volume)
    Path:	/usr/share/ca-certificates
QoS Class:	Burstable
Tolerations:	<none>
No events.
```

**Comment by Raffo** [comment]
updating the PR.

**Comment by hjacobs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
