### PR TITLE
Allow prometheus to scrape local coredns pods

### PR DESCRIPTION
**Pull request by linki**
The Service is required to allow Prometheus to find the CoreDNS DaemonSet Pods.

The firewall needs to be opened because the Pod IPs are node IPs and prometheus needs to access them from another node.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
See my comment here: https://github.com/zalando-incubator/kubernetes-on-aws/pull/1604/files#r240932080 do we actually need the extra service for this or could we re-use the existing coredns service?

**Comment by szuecs** [comment]
@mikkeloscar good question, but in any case we need to create a new dashboard and add/change the selector in zmon checks/alerts. After switch we can cleanup the checks and dashboards.
Do you think it is a blocker to roll out ?

**Comment by mikkeloscar** [comment]
I don't think it's a blocker, it just seems like extra work to roll out an extra service and then remove it at a later point unless there is a technical reason for doing it.

**Comment by njuettner** [comment]
👍

**Comment by linki** [comment]
:+1:

**Pull request merged**
