### PR TITLE
Bump dashboard to v1.4.2

### LINKED ISSUE #64: Update Kubernetes Dashboard to v1.4.2
We are using 1.4.0, but 1.4.2 is available: https://github.com/kubernetes/dashboard/releases/tag/v1.4.2

### PR DESCRIPTION
**Pull request by mikkeloscar**
https://github.com/kubernetes/dashboard/releases/tag/v1.4.2

Fix #64

### CODE REVIEW

**Comment by hjacobs** [comment]
@mikkeloscar let's also fix #63 in this PR

**Comment by mikkeloscar** [comment]
Done

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
