### PR TITLE
Webhook support DELETE/Debugger role + switch to Teams API 

### PR DESCRIPTION
**Pull request by linki**
Allows users owning the DELETE role to delete some resources.
_____
Includes switch from users API to teams API, bumped version to v0.3.3

### CODE REVIEW

**Comment by gargravarr** [comment]
:+1:

**Comment by ideahitme** [comment]
this PR includes switch from users api to teams api as well. I think @mikkeloscar is adding Debug role handling into the webhook as well, can we get it into this PR as well ?

**Comment by mikkeloscar** [comment]
I updated it to the version with `Debugger` role support.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
