### PR TITLE
Disabled acces log by default

### PR DESCRIPTION
**Pull request by arjunrn**
Skipper access logs should be an opt-in from now on.

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by femueller** [comment]
👍

**Review by femueller — APPROVED** [review]

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
Can you delete the default as well?

**Comment by arjunrn** [comment]
> Can you delete the default as well?

How do you mean?

**Comment by aermakov-zalando** [comment]
@arjunrn I'm talking about [this line](https://github.com/zalando-incubator/kubernetes-on-aws/blob/b53b7785a595acc296aa3bbaa68911b994470093/cluster/config-defaults.yaml#L20).

**Comment by arjunrn** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Pull request merged**
