### PR TITLE
Add cronjob-fixer

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Add a very simple application to automatically fix CronJobs affected by the [>100 missed execution issue](https://github.com/kubernetes/kubernetes/issues/42649).

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
(We could also run this as a cronjob :joy:)

**Comment by aermakov-zalando** [comment]
🤔

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
