### PR TITLE
coredns: enable pprof

### PR DESCRIPTION
**Pull request by aermakov-zalando**
This way we can find out what's using so much memory.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by linki** [comment]
:+1:

**Comment by linki** [comment]
Docs state that [it can be slow](https://github.com/coredns/coredns/tree/master/plugin/pprof). Since it's already used in production should we rather put it behind a config item?

**Comment by aermakov-zalando** [comment]
@linki it's only slow if you use it, just enabling it doesn't do anything. keeping it disabled is also pretty useless, since enabling it would just terminate the pods that you'd want to look at.

**Comment by linki** [comment]
I see. I thought it would be slower merely by enabling pprof.

**Pull request merged**
