### PR TITLE
Roll ingress-controller version with HTTP out to alpha channel

### PR DESCRIPTION
**Pull request by mikkeloscar**
Rolls the changes from #325 out to alpha channel clusters.

### CODE REVIEW

**Comment by hjacobs** [comment]
@mikkeloscar will this automatically change/modify all existing ALBs or how do we migrate them (adding the port 80 listener)?

**Comment by mikkeloscar** [comment]
@hjacobs no, it does not add them automatically to existing ALBs https://github.com/zalando-incubator/kube-ingress-aws-controller/pull/28

I will have to add the listener manually for all the relevant ALBs.

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
