### PR TITLE
Use open source vegeta image

### PR DESCRIPTION
**Pull request by linki**
The old vegeta image isn't available anymore. Re-pushed it to get it back.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
@linki There is an error in the new image. Logs from the container:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2  100     2    0     0   2000      0 --:--:-- --:--:-- --:--:--  2000
/attack.sh: line 24: /vegeta: cannot execute binary file: Exec format error
OK% 
```

**Comment by linki** [comment]
Ah, right. I had to built it manually, on my ARM mac 🤦

**Comment by linki** [comment]
Proper multi-arch image with a pipeline is here: https://github.bus.zalan.do/teapot/calibrated-loadtest/pull/8. It's more work than expected so this approach is just to unblock us.

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
