### PR TITLE
chore: use latest version of ingress controller

### PR DESCRIPTION
**Pull request by linki**
* ~~Support for multiple subnets~~ support the old KubernetesCluster tag used by kops 

/cc @szuecs

### CODE REVIEW

**Comment by mikkeloscar** [comment]
> Support for multiple subnets

It's not for supporting multiple subnets but for supporting the old `KubernetesCluster` tag used by kops :)

**Comment by linki** [comment]
I was tricked into this :grimacing:

**Comment by linki** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
