### PR TITLE
beta-to-beta-1.10

### PR DESCRIPTION
**Pull request by mikkeloscar**
* **alpha-to-beta**
   <sup>Merge pull request #1405 from zalando-incubator/alpha-to-beta</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **alpha-to-beta**
   <sup>Merge pull request #1402 from zalando-incubator/alpha-to-beta</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1401 from zalando-incubator/dev-to-alpha</sup>
* (No message)
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Update kube-ingress-aws-controller image version**
   <sup>Merge pull request #1399 from zalando-incubator/ingress-controller-image-update</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1398 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Go back to Kubelet's built-in cAdvisor**
   <sup>Merge pull request #1397 from zalando-incubator/revert-cadvisor</sup>
* **alpha-to-beta**
   <sup>Merge pull request #1396 from zalando-incubator/alpha-to-beta</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **Dev to alpha**
   <sup>Merge pull request #1394 from zalando-incubator/dev-to-alpha</sup>
* **Update ExternalDNS to v0.5.6**
   <sup>Merge pull request #1395 from zalando-incubator/linki-patch-1</sup>
* **Updating AWS Ingress Controller version**
   <sup>Merge pull request #1393 from zalando-incubator/update-ingress-controller</sup>
* **Update zmon-aws-agent**
   <sup>Merge pull request #1391 from zalando-incubator/update-aws-agent</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Update to Kubernetes 1.11**
   <sup>Merge pull request #1198 from zalando-incubator/kube-1.11</sup>
* **dev-to-kube-1.11**
   <sup>Merge pull request #1389 from zalando-incubator/dev-to-kube-1.11</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1390 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1387 from zalando-incubator/dev-to-alpha</sup>
* **update etcd-backup**
   <sup>Merge pull request #1388 from zalando-incubator/update-etcd-backup</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Disable CFS quota by default**
   <sup>Merge pull request #1386 from zalando-incubator/disable-quota-default</sup>
* **Update to v1.11.3**
   <sup>Merge pull request #1383 from zalando-incubator/v1.11.3</sup>
* **Use the latest Docker version by default**
   <sup>Merge pull request #1384 from zalando-incubator/upstream_docker_default</sup>
* **update ingress controller**
   <sup>Merge pull request #1382 from zalando-incubator/fix/tg-issues</sup>
* **dev-to-kube-1.11**
   <sup>Merge pull request #1381 from zalando-incubator/dev-to-kube-1.11</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1380 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Added my pubkey to the worker nodes.**
   <sup>Merge pull request #1377 from zalando-incubator/arjun-ssh-keys</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1379 from zalando-incubator/dev-to-alpha</sup>
* **dev-to-kube-1.11**
   <sup>Merge pull request #1378 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **skipper update to add accessLogDisabled() filter**
   <sup>Merge pull request #1376 from zalando-incubator/skipper/disable-logging-filter</sup>
* (No message)
   <sup>Merge branch 'dev' into skipper/disable-logging-filter</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1374 from zalando-incubator/dev-to-alpha</sup>
* **dev-to-kube-1.11**
   <sup>Merge pull request #1375 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **change kms string prefix that is used by clm**
   <sup>Merge pull request #1373 from zalando-incubator/feature/skipper-opentracing</sup>
* **deploy lightstep skipper ingress**
   <sup>Merge pull request #1371 from zalando-incubator/feature/skipper-opentracing</sup>
* **Dev to kube 1.11**
   <sup>Merge pull request #1372 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **platformcredentialsset: add status subresource**
   <sup>Merge pull request #1370 from zalando-incubator/pcs-add-status</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1369 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Martin Linkhorst <martin.linkhorst@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Bump the agent version to 0.1-a56-zv2**
   <sup>Merge pull request #1368 from avaczi/update-zmon-agent-core-to-56-zv2-2</sup>
* **Update CoreOS**
   <sup>Merge pull request #1366 from zalando-incubator/update-ami</sup>
* **Dev to kube 1.11**
   <sup>Merge pull request #1361 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **Dev to kube 1.11**
   <sup>Merge pull request #1357 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **Remove deprecated --allow-privileged kubelet flag**
   <sup>Merge pull request #1354 from zalando-incubator/rm-allow-privileged-flag</sup>
* **Dev to kube 1.11**
   <sup>Merge pull request #1347 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **cadvisor: add limits**
   <sup>Merge pull request #1340 from zalando-incubator/cadvisor-1.11</sup>
* **Run cAdvisor as a daemonset**
   <sup>Merge pull request #1339 from zalando-incubator/cadvisor-1.11</sup>
* **Update 1.11 branch**
   <sup>Merge pull request #1337 from zalando-incubator/dev-to-kube-1.11</sup>
* (No message)
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **dev-to-kube-1.11**
   <sup>Merge pull request #1331 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Arjun Naik <arjun.naik@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* **dev-to-kube-1.11**
   <sup>Merge pull request #1326 from zalando-incubator/dev-to-kube-1.11</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-kube-1.11</sup>
* (No message)
   <sup>Merge branch 'dev' into kube-1.11</sup>
* (No message)
   <sup>Merge branch 'dev' into kube-1.11</sup>
* **ZMON: use a user-defined priority class**
   <sup>Merge pull request #1310 from zalando-incubator/fix-zmon</sup>
* **ClusterAutoscaler update**
   <sup>Merge pull request #1301 from zalando-incubator/update-autoscaler-1.11</sup>
* **Kube 1.11 patch**
   <sup>Merge pull request #1299 from zalando-incubator/kube-1.11-patch</sup>
* (No message)
   <sup>Merge branch 'dev' into kube-1.11-patch</sup>
* (No message)
   <sup>Merge branch 'dev' into kube-1.11</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <m@moscar.net>

  # Conflicts:
  #	cluster/manifests/kube-proxy/daemonset.yaml
  #	cluster/node-pools/master-default/userdata.clc.yaml
  #	cluster/node-pools/worker-default/userdata.clc.yaml
  **
   <sup>Merge branch 'dev' into kube-1.11</sup>

### CODE REVIEW

**Comment by szuecs** [comment]
We should be better in what an update of a component provides.
We have at least 5x "Update X" without telling what the update fixes or which feature it enables

**Comment by aermakov-zalando** [comment]
I wanted to just switch the production clusters to `beta`. Do we really need a separate PR?

**Comment by mikkeloscar** [comment]
@aermakov-zalando I wanted to run e2e on these changes, but it doesn't work anyway...

**Comment by szuecs** [comment]
we swith it through cluster-registry first

**Pull request closed without merging**
