### PR TITLE
Update admission-controller to support StatefulSets with PVCs

### PR DESCRIPTION
**Pull request by linki**
This allows to process the `zalando.org/topology-spread` annotation on StatefulSets.

### CODE REVIEW

**Comment by linki** [comment]
See discussion and merge after https://github.com/zalando-incubator/kubernetes-on-aws/pull/5506 and related PRs

**Comment by linki** [comment]
Will be done in https://github.com/zalando-incubator/kubernetes-on-aws/pull/5506

**Comment by linki** [comment]
Nevermind, let's do it here since the other PR contains unrelated changes now.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
👍

**Pull request merged**
