### PR TITLE
Updated etcd backup cronjob to run every minute.

### PR DESCRIPTION
**Pull request by gargravarr**
Signed-off-by: Rodrigo Reis <rodrigo@zalando.de>

### CODE REVIEW

**Comment by hjacobs** [comment]
Do we backup every minute then? Is there any potential negative impact?

**Comment by gargravarr** [comment]
Yes, it takes about 20 seconds to complete the job.

**Comment by gargravarr** [comment]
Let's try it in dev channel and see what load it puts on etcd cluster. We can then adjust it based on that.

**Comment by gargravarr** [comment]
@hjacobs actually we've just set stups-test channel to run based on this branch over the weekend. Monday we'll see how it went.

**Comment by mikkeloscar** [comment]
Note: with the current retention policy on the s3 bucket (7 days) this will change the storage size from `~6Gi` -> `~350Gi` based on one example (search cluster).

**Comment by hjacobs** [comment]
I think it would make sense to use something more reasonable like 10 minutes as interval?

**Comment by gargravarr** [comment]
@mikkeloscar what is the value of having a 7 days retention policy? Is it safe to reduce this to 1 or 2 days?

**Comment by gargravarr** [comment]
@hjacobs etcd-backup job takes 20s to complete. Backing up every minute will increase the probability of restoring etcd to a consistent state, in case of failure.

**Comment by mikkeloscar** [comment]
> @mikkeloscar what is the value of having a 7 days retention policy? Is it safe to reduce this to 1 or 2 days?

@gargravarr considering we don't trust backups that are 1 hour old there's no real value in keeping the backups for that long. It's only for safety IMO i.e. if we don't notice that an etcd cluster is down for some hours, then we still have "some" backups available which is better than nothing.

It's IMO reasonable to lower the retention to 48 hours.

**Comment by gargravarr** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
