### PR TITLE
use zmon-worker in version v209-py2eol-45-g10d91c6

### PR DESCRIPTION
**Pull request by pheanex**
This ships the feature in zmon-worker to query scalyr with absolute timestamps
https://github.com/zalando-zmon/zmon-worker/pull/418

### CODE REVIEW

**Comment by pheanex** [comment]
:+1:

**Comment by femueller** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by pitr** [comment]
this version string is incomplete, see #2676 with fix

**Pull request merged**
