### PR TITLE
Update kube-downscaler to 0.6 (stackset support)

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update to version 0.6 which supports scaling down stacksets.

https://github.com/hjacobs/kube-downscaler/releases/tag/0.6

### CODE REVIEW

**Comment by hjacobs** [comment]
This is not enough to enable StackSet support, you also need to add `--kind=stackset` and `--kind=deployment`.

**Comment by mikkeloscar** [comment]
Ah ok, I see. Fixed now.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
