### PR TITLE
Update to kubernetes v1.5.3

### LINKED ISSUE #282: Test and update to Kubernetes v1.5.3
v1.5.3 is out: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v153

Nothing stands out to me in the CHANGELOG, seems like a fairly simple update in our setup,

### PR DESCRIPTION
**Pull request by mikkeloscar**
https://github.com/kubernetes/kubernetes/releases/tag/v1.5.3

Fix #282 

Will test this with the e2e setup.

### CODE REVIEW

**Comment by hjacobs** [comment]
@mikkeloscar what does "Can't set status; build succeeded." mean?

**Comment by mikkeloscar** [comment]
@hjacobs I think jenkins failed to set the status (like travis and zappr does) because the robot user didn't have access to the repo, is fixed now though.

**Comment by hjacobs** [comment]
Related PR for `zkubectl`: https://github.com/zalando-incubator/zalando-kubectl/pull/29

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:(

**Comment by hjacobs** [comment]
@mikkeloscar I messed up with git haha --- I'm just a noob :smirk:

**Pull request closed without merging**
