### PR TITLE
Allow zmon-agent to describe dynamodb tables

### PR DESCRIPTION
**Pull request by mikkeloscar**
Allow zmon-agent to describe dynamodb tables in order to create dynamodb entities.

### CODE REVIEW

**Comment by mohabusama** [comment]
👍

**Comment by mohabusama** [comment]
@mikkeloscar can we include those as well:
```
rds:Describe*
rds:ListTagsForResource
```

**Comment by mikkeloscar** [comment]
@mohabusama that's already there.

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
