### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by szuecs**
* **fix skipper-graceful-start**
   <sup>Merge pull request #1499 from zalando-incubator/fix/skipper-graceful-start</sup>
* **Update the VPA CRD version.**
   <sup>Merge pull request #1496 from zalando-incubator/vpa-crd-bump</sup>
* **Adding draft manifests for vertical pod autoscaler**
   <sup>Merge pull request #1488 from zalando-incubator/adding-vpa</sup>
* **do not log websocket content**
   <sup>Merge pull request #1494 from zalando-incubator/fix/websocket-logging</sup>
* **Upgrade ZMON agents**
   <sup>Merge pull request #1495 from zalando-incubator/upgrade-zmon-aws-agent</sup>

### CODE REVIEW

**Comment by szuecs** [comment]
@muaazsaleem @arjunrn is the VPA setup ready for alpha?

**Comment by arjunrn** [comment]
It's feature gated so there's no harm in releasing it.

**Comment by jrake-revelant** [comment]
if this needs a rolling update anyway, could you sneak in my keys?

**Comment by szuecs** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
