### PR TITLE
Dev to kube 1.14

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Merge the recent changes from `dev`. Note that `setup_modules.sh` was changed to checkout the 1.14 branch instead of a tag because of the stupid `github.com/renstrom/dedent` rename.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
Looks like this fails because the e2e tests start by creating the previous cluster and then do an update. However the previous cluster doesn't come up because the old AMI doesn't exist.

**Comment by linki** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
