### PR TITLE
Promote dev to alpha

### PR DESCRIPTION
**Pull request by linki**
Notable changes:
* Add support for our own etcd proxy
* Prepare kube-proxy daemonset rollout
* Prepare flannel daemonset rollout
* Add PodCIDR Controller for flannel migration
* Use latest version of ingress controller
* Remove ClusterID tag frome CF
* Expire old etcd backups
* Upgrade zmon-agent to include deep-link (clean tag)

### CODE REVIEW

**Comment by linki** [comment]
Let's give it a day or two on stups-test before merging this to stups.

**Comment by linki** [comment]
* Add Kubernetes Egress controller

Currently blocks the rollout. Should we revert it in order to proceed?

**Comment by gargravarr** [comment]
I think we should revert it, yes.

**Comment by mikkeloscar** [comment]
This PR is targeting `dev` just FYI :)

**Comment by linki** [comment]
I reverted the Egress feature directly on this branch as it's fairly safe (just removes a deployment and IAM role) and we can use `dev` to test the "broken" version.

**Comment by szuecs** [comment]
:+1:

**Comment by Raffo** [comment]
👍

**Pull request merged**
