### PR TITLE
Update to Kubernetes v1.9.3

### PR DESCRIPTION
**Pull request by mikkeloscar**
WIP to start testing v1.9.3. Not ready for merge!

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#v190

**Note:** we should upgrade to etcd 3.1+ before rolling out v1.9.

### CODE REVIEW

**Comment by hjacobs** [comment]
Kubernetes v1.9.3 is out now.

**Comment by aermakov-zalando** [comment]
If we merge #841 first, we'll need to change the autoscaler configuration a bit (version to 1.1.0 and set the minimum priority to the buffer pod priority).

**Comment by linki** [comment]
@aermakov-zalando Since we merged #841 first can you take care of updating the config that you mentioned above?

**Comment by mikkeloscar** [comment]
@aermakov-zalando yes, please just push to this PR with the updates needed.

**Comment by aermakov-zalando** [comment]
@linki @mikkeloscar done.

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
