### PR TITLE
fix role mapping for the default serviceaccount

### PR DESCRIPTION
**Pull request by szuecs**
This is a hotfix to fix the default serviceaccount which was not mapped to a role

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Will you tag the version before we merge?

**Comment by szuecs** [comment]
I checked with a test cluster that the fix really sets the role correctly.

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
