### PR TITLE
feat: add role to write skipper config map (#1955)

### LINKED ISSUE #1955: Add role to write skipper config map
Instead of adding the API monitoring controller to the kube-system namespace, we decided to create access rights to write the skipper-default-filters config map.

This config map will be read by skipper (see https://github.com/zalando/skipper/pull/983).

### PR DESCRIPTION
**Pull request by tkrop**
fixes #1955.

Replaces #1927.

### CODE REVIEW

**Comment by zeitlinger** [comment]
:+1:

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Review by maxim-tschumak — APPROVED** [review]

**Comment by tkrop** [comment]
We tested this completely in `playground`. @aermakov-zalando was supporting in applying the resource for `kube-system`. Our `api-monitoring-controller` is successfully updating the configmap.

**Comment by szuecs** [comment]
:+1:

**Comment by tkrop** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
