### PR TITLE
Fix DENY policy so oversight is easier

### PR DESCRIPTION
**Pull request by linki**
https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874 with e2e tests

### CODE REVIEW

**Comment by msooszalando** [comment]
Ah, the problem is the single quotes maybe?

**Comment by linki** [comment]
No, I thought that initially, too, but that's not it.

I tracked it down to the two actions that I commented out. If you pick one of them it will fail. (The e2e tests are currently failing for another reason.)

If there's no fundamental reason why you cannot Deny those actions (e.g. List on a Bucket item might be invalid?) then I suspect it might just contradict some other statement in the role?

**Comment by linki** [comment]
@msooszalando Do you still need this. We had to rollback your initial PR https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874

**Comment by linki** [comment]
@idotan Do you still need this? We had to revert the original PR https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874

**Comment by mikkeloscar** [comment]
@linki I believe it fails because `Create` and `Update` actions are not relevant for a bucket resource. E.g. the create/update actions are the following:

```
CreateAccessPoint
CreateAccessPointForObjectLambda
CreateBucket
CreateJob
CreateMultiRegionAccessPoint
UpdateJobPriority
UpdateJobStatus
```

Which doesn't make sense to do on a bucket I guess.

The better solution here would be to use `NotAction` and only list the action we want to allow with this change, instead of trying to list all the ones to be denied.

https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html

**Comment by linki** [comment]
Can we close this?

This was an attempt to bring back the changes of https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874 (by @msooszalando) which got reverted.

I don't know what the purpose actually was.

**Comment by mikkeloscar** [comment]
The goal was to read bucket policy information e.g. by the security audit role, but since this hasn't been brought up in 6 months, let's close it for now.

**Pull request closed without merging**
