### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* **Add a missing priority class**
   <sup>Merge pull request #1882 from zalando-incubator/fix-janitor-priority</sup>
* **Disable automatic transparent hugepages**
   <sup>Merge pull request #1880 from zalando-incubator/hugepages</sup>
* **Increase Fluentd Buffer Queue Size**
   <sup>Merge pull request #1877 from zalando-incubator/increase-fluentd-queue</sup>
* **Priority classes**
   <sup>Merge pull request #1879 from zalando-incubator/priority-classes</sup>
* **Kubernetes v1.12.6 + Use Docker images for individual components instead of hyperkube**
   <sup>Merge pull request #1825 from zalando-incubator/separate-images</sup>
* **Enable logging of .svc DNS names in CoreDNS**
   <sup>Merge pull request #1874 from zalando-incubator/log-svc-names-coredns</sup>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
👎

**Comment by aermakov-zalando** [comment]
Investigate if there are any controller-manager issues in 1.12.6.

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
