### PR TITLE
allow zmon to list step functions

### PR DESCRIPTION
**Pull request by vetinari**
and see executions

### CODE REVIEW

**Comment by vetinari** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by simonq80** [comment]
:+1:

**Comment by simonq80** [comment]
@szuecs / @katyanna / @linki could we get a +1 on this PR please? we have a zmon-worker PR https://github.bus.zalan.do/metrics/zmon-worker/pull/187 waiting on it.

**Comment by john-coleman** [comment]
:+1:

**Comment by katyanna** [comment]
👍

**Pull request merged**
