### PR TITLE
Update to Kubernetes v1.19.8 [node rolling]

### PR DESCRIPTION
**Pull request by mikkeloscar**
https://github.com/kubernetes/kubernetes/releases/tag/v1.19.8

* Updates `docker`: `5:19.03.13~3-0~ubuntu-focal` -> `5:20.10.3~3-0~ubuntu-focal`
* Updates `containerd`: `1.3.9-1` -> `1.4.3-1`
* Updates `nvidia-container-runtime`: `3.4.0-1` -> `3.4.2-1`

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
This also updates Docker, right?

**Comment by mikkeloscar** [comment]
@aermakov-zalando True, clarified the updates in the description.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
