### PR TITLE
preserve incoming hostname in ingress

### PR DESCRIPTION
**Pull request by aryszka**
set the flag to preserve the incoming host during ingress

### CODE REVIEW

**Comment by hjacobs** [comment]
@aryszka did you create a test cluster with this setting?

**Comment by Raffo** [comment]
I will rebase master here to make sure because the changes in this PR work. The current status of the PR is not working in some setups with ingress.

**Comment by hjacobs** [comment]
@Raffo what is not working atm?

**Comment by Raffo** [comment]
I'm testing it after updating from master. Before, the ingress controller was not working at all. The current setup with Ingress has problems when running in setups with multiple clusters per account which affect the ease of tests, but I would address this in a separate issue and try only to focus on the feature of this PR.

**Comment by Raffo** [comment]
This feature works apart from the bug found in the ingress controller. I will report and fix that separately.

**Comment by Raffo** [comment]
👍

**Comment by Raffo** [comment]
👍

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
