### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* **Make cadvisor resources configurable**
   <sup>Merge pull request #1684 from zalando-incubator/cadvisor-increase-mem</sup>
* **Fix/resources**
   <sup>Merge pull request #1680 from zalando-incubator/fix/resources</sup>
* **fix logging issue when we crash on unexpected input**
   <sup>Merge pull request #1683 from zalando-incubator/fix/app-crash-and-no-log</sup>
* **add pprof endpoint to skipper-ingress**
   <sup>Merge pull request #1675 from zalando-incubator/skipper/enable-pprof</sup>
* **Update kube-metrics-adapter with fix to ZMON collector**
   <sup>Merge pull request #1673 from zalando-incubator/kube-metrics-adapter-zmon-fix</sup>
* **Cluster Lifecycle Controller integration**
   <sup>Merge pull request #1589 from zalando-incubator/clc</sup>
* **kube-job-cleaner: update to master-12**
   <sup>Merge pull request #1674 from zalando-incubator/bump-job-cleaner</sup>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:-1:

**Comment by mikkeloscar** [comment]
`cadvisor` config is wrong. I'll update the PR.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
