### PR TITLE
Ndots kube system

### PR DESCRIPTION
**Pull request by njuettner**
Only for testing purposes right now

### CODE REVIEW

**Comment by njuettner** [comment]
@mikkeloscar please review, I omitted VPA and CoreDNS.

**Comment by mikkeloscar** [comment]
@njuettner anything which uses `hostNetwork` should use the default `/etc/resolv.conf` from the node, so the custom setting shouldn't be needed (This includes CoreDNS). I'm actually curious what happens when you set it, I would expect that it just ignores it, but maybe it injects the ndots setting?

Otherwise it looks good, we should try to run e2e and see if everything works with this in place!

**Comment by njuettner** [comment]
> @njuettner anything which uses `hostNetwork` should use the default `/etc/resolv.conf` from the node, so the custom setting shouldn't be needed (This includes CoreDNS). I'm actually curious what happens when you set it, I would expect that it just ignores it, but maybe it injects the ndots setting?
> 
> Otherwise it looks good, we should try to run e2e and see if everything works with this in place!

Indeed, I totally missed it 😄. Thanks! 
I've just removed the ndots for the hostNetwork files.

**Comment by szuecs** [comment]
> > @njuettner anything which uses `hostNetwork` should use the default `/etc/resolv.conf` from the node, so the custom setting shouldn't be needed (This includes CoreDNS). I'm actually curious what happens when you set it, I would expect that it just ignores it, but maybe it injects the ndots setting?
> > Otherwise it looks good, we should try to run e2e and see if everything works with this in place!
> 
> Indeed, I totally missed it smile. Thanks!
> I've just removed the ndots for the hostNetwork files.

It depends.
hostNetwork with `dnsPolicy: ClusterFirstWithHostNet` should have them.

**Comment by njuettner** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
