### PR TITLE
Enable merge build for protected branches to update pipeline cache

### PR DESCRIPTION
**Pull request by AlexanderYastrebov**
See https://github.com/zalando-incubator/kubernetes-on-aws/pull/4893#issuecomment-1012292921

Signed-off-by: Alexander Yastrebov <alexander.yastrebov@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
hmm please rebase and squash to one commit

**Comment by AlexanderYastrebov** [comment]
@szuecs The tests have finally passed

**Comment by mikkeloscar** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
