### PR TITLE
alpha to beta

### PR DESCRIPTION
**Pull request by Raffo**
This brings changes from latest alpha to beta clusters.

### CODE REVIEW

**Comment by szuecs** [comment]
@Raffo external dns did not created a DNS entry for service type LB
Summarizing 1 Failure:
External DNS creation [It] Should create DNS entry [Slow] [Zalando] 
.../kubernetes-e2e-tests/external_dns.go:82

**Comment by Raffo** [comment]
Build is flaky, but I think it's okay to merge (it's the same as alpha).

**Comment by Raffo** [comment]
👍

**Comment by mikkeloscar** [comment]
Only externaldns test was flaky which unrelated to these changes.

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
