### PR TITLE
enable oauthTokeninfo filters

### PR DESCRIPTION
**Pull request by szuecs**
enable oauth filter in skipper and set dependent on the environment prod and sandbox endpoints

increase version
- fix invalid connection header issue reported via slack channel (https://github.com/zalando/skipper/issues/699)
- use 308 in Kubernetes HTTPS redirect instead of 301 (https://github.com/zalando/skipper/issues/695)
- do not add annotation filters to LB decision routes (https://github.com/zalando/skipper/issues/694)
- Added ID of the matching route to open tracing span (https://github.com/zalando/skipper/issues/692)
- sort routing table output on support endpoint (https://github.com/zalando/skipper/issues/681)
- add option to strip query strings from request URIs in the access logs (https://github.com/zalando/skipper/issues/392)

### CODE REVIEW

**Comment by aryszka** [comment]
:+1:

**Comment by szuecs** [comment]
@aryszka we wait for the zalando-tests e2e passing

**Comment by linki** [comment]
We could also revive https://github.com/zalando-incubator/kubernetes-on-aws/pull/918 to make it "Kubernetes-native". @szuecs WDYT?

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
