### PR TITLE
Update to v1.18.12

### PR DESCRIPTION
**Pull request by aermakov-zalando**
[Changes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md/#changelog-since-v11810).

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
test

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
