### PR TITLE
Kubernetes v1.6.1

### LINKED ISSUE #331: Kubernetes v1.6.0
Release candidate is now available, we should start to try it out: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v160-rc1

### PR DESCRIPTION
**Pull request by hjacobs**
Fixes #331

**Things TODO before merge:**

* [x] Check new default volume class (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#volume)
* [x] update kube-dns
* [x] Build/use new rescheduler image (registry.opensource.zalan.do)
* [x] test with 1.6.0 conformance tests
* [x] Slim CF template down to accepted size...

* [x] Manual tests
    * [x] Update from 1.5.5 to 1.6.0
    * [x] daemonset rolling upgrade (requires kubectl v1.6.0 in the CLM to apply `updateStrategy`)
    * [ ] rescheduler
    * [x] volume class (have to use `storageclass.beta.kubernetes.io/is-default-class: "true"` until https://github.com/kubernetes/kubernetes/pull/43945 is upstreamed)
    * [x] webhook (inspect logs and watch out for blocked requests)

### CODE REVIEW

**Comment by hjacobs** [comment]
Kubectl update to v1.6.0: https://github.com/zalando-incubator/zalando-kubectl/pull/35

**Comment by mikkeloscar** [comment]
The `kube-dns-autoscaler` deployment was missing a `matchLabel` selector, this means we will have to remove the deployment in every cluster otherwise CLM will fail to apply the updated deployment because the labels won't match.

This won't affect operation but is just a manual task.

**Comment by mikkeloscar** [comment]
Despite the `kube-dns-autoscaler` issue, upgrading from a v1.5.5 to v1.6.0 cluster worked fine.

**Comment by mikkeloscar** [comment]
Bumped to v1.6.1

**Comment by mikkeloscar** [comment]
Working test: https://teapot.ci.zalan.do/job/Jenkins%20Conformance%20e2e/144/

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
