### PR TITLE
Bump Skipper to the newest version and enable OpenTracing backend name tag

### PR DESCRIPTION
**Pull request by marcinzaremba**
Basically bring https://github.com/zalando/skipper/pull/1495 to live

### CODE REVIEW

**Comment by marcinzaremba** [comment]
@aryszka Can you please review?

**Comment by aryszka** [comment]
:+1:

**Comment by marcinzaremba** [comment]
👍

**Comment by aryszka** [comment]
Thanks Marcin!

**Comment by jrake-revelant** [comment]
👍

**Comment by aryszka** [comment]
includes:

- fix routegroup crd schema for json validation
- OIDC auth filters to return raw ID Token
- JW: fixing typo in OauthState which was confusing in the log output
- lua scripting improvements
- setting the parentSpan for response filters
- tracingTag with a backend name for RouteGroup-generated routes

**Pull request merged**
