### PR TITLE
Alpha to db alpha

### PR DESCRIPTION
**Pull request by hjacobs**
Notable changes:

* Kubernetes v1.6.2
* External DNS replacing Mate
* Webhook version bump
* kube2iam version bump

### CODE REVIEW

**Comment by hjacobs** [comment]
According to @ideahitme we might need to change some External DNS setting (FQDN template) for the "db" cluster...

**Comment by ideahitme** [comment]
afaik `db` cluster is using mate's "dns name generation from template" feature. We will probably have to update external-dns manifest to simulate this behaviour

**Comment by linki** [comment]
I count 34 services with an ELB. All are using the `mate` annotation and don't use the template.

double-checking with the source code. The operator does create the services with the annotation: https://github.bus.zalan.do/acid/postgres-operator/blob/master/pkg/cluster/k8sres.go#L264

**Comment by linki** [comment]
This rollout will be supported by some manual work. So please don't merge.

**Comment by hjacobs** [comment]
:+1:

**Comment by linki** [comment]
👍

**Pull request merged**
