### PR TITLE
use eu as default scalyr region for zmon queries

### PR DESCRIPTION
**Pull request by pheanex**
@anton-ryzhov @vwiessner @marcinzaremba please review

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
Is `WORKER_SCALYR_REGION` documented anywhere? How is it applied?

**Comment by pheanex** [comment]
@anton-ryzhov See https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/main.py#L78

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
