### PR TITLE
fix apimonitoring filter

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by szuecs** [comment]
@maxim-tschumak this is teapot only approve, which makes sense. All of teapots have to be aware of the change.

**Comment by szuecs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
