### PR TITLE
Add a `go mod tidy` check during CI

### PR DESCRIPTION
**Pull request by jonathanbeber**
This commit adds another CI step to check whether the `go.mod` and
`go.sum` is consistent.

### CODE REVIEW

**Comment by jonathanbeber** [comment]
#3854 broke merge to kube1.19 again. It was just `go.sum`. I hope this check helps us to avoid that and keep `go.sum` clean.

**Comment by jonathanbeber** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Pull request merged**
