### PR TITLE
Add Zak and Rodrigo as maintainers

### PR DESCRIPTION
**Pull request by katyanna**
Add @zaklawrencea and @rodrigodelmonte to maintainers list on the zappr config file.

### CODE REVIEW

**Comment by katyanna** [comment]
:+1:

**Comment by rodrigodelmonte** [comment]
:+1:

**Comment by katyanna** [comment]
you actually need that too, @rodrigodelmonte

**Comment by katyanna** [comment]
:+1:

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
