### PR TITLE
Fix RPS based scaling with stackset

### PR DESCRIPTION
**Pull request by mikkeloscar**
Fixes RPS based scaling for stacksets: https://github.com/zalando-incubator/stackset-controller/pull/232

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
:+1:

**Comment by linki** [comment]
FYI: This was also picked up by the Renovate bot: https://github.com/zalando-incubator/kubernetes-on-aws/pull/3405

**Comment by linki** [comment]
Has been done manually in https://github.com/zalando-incubator/kubernetes-on-aws/pull/3424. Bot should close this PR soon.

**Pull request merged**
