### PR TITLE
adjust default scaling for zmon-worker

### PR DESCRIPTION
**Pull request by vetinari**
please clear the registry when rolling out this change

Signed-off-by: Hanno Hecker <hanno@zalando.de>

### CODE REVIEW

**Comment by vetinari** [comment]
..redone #1505 because of DCO

**Comment by gargravarr** [comment]
We'll merge it tomorrow after 13:00 CET

**Comment by gargravarr** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
