### PR TITLE
Migrate more images to the new registry

### PR DESCRIPTION
**Pull request by linki**
A couple more images that are ready to be pulled from the new registry (all are available as both amd64 and arm64).
* skipper
* cluster-autoscaler

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
👍

**Comment by linki** [comment]
Since there's a bit of a version bump in skipper, I'll ping @szuecs

**Comment by szuecs** [comment]
:-1:

**Comment by szuecs** [comment]
please update to latest skipper with patch version 218, thanks!

**Comment by linki** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
