### PR TITLE
add opentracing headers to tokeninfo and tokenintrospection filters 

### PR DESCRIPTION
**Pull request by szuecs**
add opentracing headers to tokeninfo and tokenintrospection filters to make these visible

https://opensource.zalando.com/skipper/reference/filters/#oauthtokeninfoanyscope
https://opensource.zalando.com/skipper/reference/filters/#oauthtokeninfollscope
https://opensource.zalando.com/skipper/reference/filters/#oauthtokeninfoanykv
https://opensource.zalando.com/skipper/reference/filters/#oauthtokeninfoallkv
https://opensource.zalando.com/skipper/reference/filters/#oauthtokenintrospectionanyclaims
https://opensource.zalando.com/skipper/reference/filters/#oauthtokenintrospectionallclaims
https://opensource.zalando.com/skipper/reference/filters/#oauthtokenintrospectionanykv
https://opensource.zalando.com/skipper/reference/filters/#oauthtokenintrospectionallkv

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by hjacobs** [comment]
@szuecs can you link the Skipper docs (about the filters)? It would be nice to know which filters you are specifically referring to.

**Comment by szuecs** [comment]
@hjacobs done

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
