### PR TITLE
add lightstep propagators to skipper

### PR DESCRIPTION
**Pull request by vetinari**
related: https://github.com/zalando/skipper/pull/1652
default is "lightstep" only

Signed-off-by: Hanno Hecker <hanno@zalando.de>

### CODE REVIEW

**Comment by muaazsaleem** [comment]
👍

**Comment by muaazsaleem** [comment]
I think a new version (tag) of skipper will also need to be rolled to the clusters to the https://github.com/zalando/skipper/pull/1652

**Comment by muaazsaleem** [comment]
Doesn't the skipper version also needs to be updated to at least [v0.12.13](https://github.com/zalando/skipper/releases/tag/v0.12.13) for these changes to actually take effect?

**Comment by vetinari** [comment]
yes

**Comment by mikkeloscar** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Comment by jonathanbeber** [comment]
Thanks @vetinari, I'm merging it.

**Pull request merged**
