### PR TITLE
Update deployment-service to master-203

### PR DESCRIPTION
**Pull request by linki**
Updates deployment-service to the latest version: https://github.bus.zalan.do/teapot/deployment-service/pull/214

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
This includes a fix for a previous PR: https://github.com/zalando-incubator/kubernetes-on-aws/pull/7722 Let's just merge it together.

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
