### PR TITLE
Fix node draining during termination

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Resolves the issues with the graceful termination unit:
 * use correct paths for kubeconfig
 * fix DNS issues in the container

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
Since we immediately restart the node (for the docker downgrade) a working node-drainer marks the node as Unschedulable and there's nothing to make it scheduleable again after reboot, right?

**Comment by aermakov-zalando** [comment]
@linki the downgrade script is a dependency for `docker.service`, so the node-drainer isn't even started until after the first reboot.

**Comment by linki** [comment]
Ah, nice :)

**Comment by aermakov-zalando** [comment]
👍

**Comment by linki** [comment]
👍

**Pull request merged**
