### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* **Fluentd integration**
   <sup>Merge pull request #1826 from zalando-incubator/fluentd-integration</sup>
* **feature: allow cluster access for deployment-discovery (#1817)**
   <sup>Merge pull request #1818 from tkrop/patch-2</sup>
* **Bump CoreOS again**
   <sup>Merge pull request #1824 from zalando-incubator/coreos-update</sup>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Comment by hjacobs** [comment]
External DNS should be tested or was it already rolled out to alpha?

**Comment by szuecs** [comment]
@hjacobs it's already rolled out and not part of this PR

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
