### PR TITLE
Cherrypick dev to alpha

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* etcd 3.3.0 -> 3.3.1
 * Increase default autoscaler utilization threshold and make it configurable

### CODE REVIEW

**Comment by hjacobs** [comment]
How did we come up with the 0.75 number for `--scale-down-utilization-threshold` and why do we change it in the first place? Is this a guesstimate or based an data/experiments?

**Comment by aermakov-zalando** [comment]
@hjacobs it's a less conservative guesstimate than the default value of 0.5, which should make the downscaling a bit more aggressive. This change also makes it configurable by changing a config item, which would allow us to experiment on live clusters to better tune the autoscaler. Considering that the production clusters should have buffer pods enabled, we could probably bump it all the way up to 0.9, but I'd start with a safer default first.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
