### PR TITLE
update skipper to support brotli encoding

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
I think `-compress-encodings` should also be configured

**Comment by szuecs** [comment]
Added this config item and use the default `gzip,deflate,br`

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by szuecs** [comment]
rebased on dev

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
