### PR TITLE
Update to v1.14.8

### PR DESCRIPTION
**Pull request by aermakov-zalando**
[Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md/#v1147)

### CODE REVIEW

**Comment by szuecs** [comment]
Wait for https://github.com/kubernetes/kubernetes/issues/82923 and rebuild the binaries

**Comment by njuettner** [comment]
Skipped v1.14.7 and added v1.14.8
Changelog: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md/#v1148

**Comment by arjunrn** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
