### PR TITLE
new mate version v0.6.1

### PR DESCRIPTION
**Pull request by ideahitme**
https://github.com/zalando-incubator/mate/releases/tag/v0.6.0 
https://github.com/zalando-incubator/mate/releases/tag/v0.6.1
need to test it on dev in teapot cluster

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by ideahitme** [comment]
will test it in a separate cluster first with this branch

**Comment by linki** [comment]
@ideahitme good for `dev`?

**Comment by Raffo** [comment]
+1 @ideahitme please remove the label if we can go with it.

**Comment by hjacobs** [comment]
According to @ideahitme there is a bug...

**Comment by hjacobs** [comment]
Bug is fixed in https://github.com/zalando-incubator/mate/pull/88 according to @ideahitme

**Comment by linki** [comment]
👍

**Comment by ideahitme** [comment]
I will do another round of testing

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
