### PR TITLE
Update kube2iam to custom version

### PR DESCRIPTION
**Pull request by mikkeloscar**
Update kube2iam to ~v0.8.2~ custom fork with this patch: https://github.com/jtblin/kube2iam/pull/108

https://github.com/jtblin/kube2iam/releases/tag/0.8.2

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
@linki I'm waiting for this to be merged: https://github.com/jtblin/kube2iam/pull/108 that's why I put `do-not-merge`.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
👍

**Pull request merged**
