### PR TITLE
Enable okta authentication by default

### PR DESCRIPTION
**Pull request by mikkeloscar**
Enable okta authentication by default in all clusters.

(Already enabled in all clusters via config-item)

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Comment by szuecs** [comment]
@mikkeloscar why can't we clean up the config item?

**Comment by mikkeloscar** [comment]
> @mikkeloscar why can't we clean up the config item?

We can, but I would propose to wait until okta is the default as it's still in a testing phase. I have added a step to remove the config item in the internal ticket tracking the okta rollout.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
