### PR TITLE
skipper: update image to use amazonlinux base image (step 1/2)

### PR DESCRIPTION
**Pull request by MustafaSaber**
[changes](https://github.com/zalando/skipper/compare/v0.21.72...v0.21.76)

- https://github.com/zalando/skipper/pull/3047
- https://github.com/zalando/skipper/pull/3048
- https://github.com/zalando/skipper/pull/3049
- https://github.com/zalando/skipper/pull/3050
- https://github.com/zalando/skipper/pull/3052

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
Needs rebase and please add list of Skipper changes similar to e.g. https://github.com/zalando-incubator/kubernetes-on-aws/pull/7366

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by MustafaSaber** [comment]
👍

**Pull request merged**
