### PR TITLE
VPAs for zmon cluster singletons

### PR DESCRIPTION
**Pull request by szuecs**
configure VPAs based on max number of config defaults and cluster registry overwrites

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Let's increase the maximum values to something bigger so we don't have to babysit them during incidents (e.g. 1/2 CPUs, 2-3 gigs of RAM for all).

**Comment by szuecs** [comment]
@aermakov-zalando done

**Comment by aermakov-zalando** [comment]
As discussed in the chat, let's drop VPA for redis for now?

**Comment by szuecs** [comment]
:+1:

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
