### PR TITLE
fix: apimonitoring was not enabled so metrics were not exposed

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by tkrop** [comment]
:+1:

**Comment by tkrop** [comment]
But I'm not sure, that this will fix the issue for *out-of-the-box* API monitoring, since if `-default-filters-dir=/etc/config/default-filters` are not set, I assume the configuration of the API monitoring is not read - isn't it?

**Comment by szuecs** [comment]
@tkrop default filters are applied at routesrv, because skipper-ingress will not use kubernetes dataclient anymore

**Comment by szuecs** [comment]
:+1:

**Comment by aryszka** [comment]
:+1:

**Pull request merged**
