### PR TITLE
adding ssh-keys for node access

### PR DESCRIPTION
**Pull request by jrake-revelant**
Add Jannis to the list of allow ssh users

### CODE REVIEW

**Comment by szuecs** [comment]
please sign your PR

**Comment by aermakov-zalando** [comment]
You could also switch to ed25519 keys. :)

**Comment by jrake-revelant** [comment]
@aermakov-zalando that is a good idea

**Comment by dionb** [comment]
:+1:

**Comment by dionb** [comment]
:+1:

**Comment by jrake-revelant** [comment]
👍

**Pull request merged**
