### PR TITLE
Update skipper version, step 2/2

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
Merge https://github.com/zalando-incubator/kubernetes-on-aws/pull/7648 before this one

+ config: support multiple default filters flag values https://github.com/zalando/skipper/pull/3084
+ build(deps): bump docker/login-action from 3.1.0 to 3.2.0 https://github.com/zalando/skipper/pull/3090
+ build(deps): bump github.com/redis/go-redis/v9 from 9.5.1 to 9.5.2 https://github.com/zalando/skipper/pull/3092
+ build(deps): bump github.com/open-policy-agent/opa-envoy-plugin from 0.64.1-envoy to 0.65.0-envoy https://github.com/zalando/skipper/pull/3093
+ metrics: add start label for prometheus counters https://github.com/zalando/skipper/pull/3089
+ Reduce errors in decision logs that are operational https://github.com/zalando/skipper/pull/3086
+ doc: review and update ingress usage docs https://github.com/zalando/skipper/pull/3094
+ build: trim path https://github.com/zalando/skipper/pull/3095
+ OPA: Add decision outcome to span https://github.com/zalando/skipper/pull/3096
+ Set log level of PHC dropping an endpoint to debug https://github.com/zalando/skipper/pull/3098

FYI https://github.com/zalando/skipper/compare/v0.21.101...v0.21.108

### CODE REVIEW

**Comment by AlexanderYastrebov** [comment]
Does it target a wrong branch?

**Comment by RomanZavodskikh** [comment]
@AlexanderYastrebov 
> Does it target a wrong branch?

No, it does target the right branch because:
+ this particular PR is simple in every point in time (1 line removed, 1 line added)
+ after merging the corresponding canary PR it is automatically redirected to be merged into dev.

If the PR is created to dev from the very beginning, the UI will show 2 lines added and 2 lines removed even after canary PR merged which could be confusing.

**Comment by RomanZavodskikh** [comment]
:+1:

**Comment by AlexanderYastrebov** [comment]
:+1:

**Pull request merged**
