### PR TITLE
dev-to-alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* **Enable zmon metrics HPA in production clusters**
   <sup>Merge pull request #1479 from zalando-incubator/kube-metrics-adapter</sup>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by aermakov-zalando** [comment]
Shouldn't the template have `{{-` instead, or does it render fine?

**Comment by mikkeloscar** [comment]
It works fine in stups-test (without what's inside the if)

**Comment by mikkeloscar** [comment]
Yup, also works with the if. (I changed it to `if eq .Environment "test"` and applied to stups-test).

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
