### PR TITLE
Support m5d instances

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Use `instance_info.InstanceStorageDevices` instead of a hard-coded path. Depends on https://github.com/zalando-incubator/cluster-lifecycle-manager/pull/108.

### CODE REVIEW

**Comment by njuettner** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Comment by njuettner** [comment]
👍

**Comment by njuettner** [comment]
pet cluster looks fine for me:

```
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     vol04b63ac805c7c73a5 Amazon Elastic Block Store               1           0.00   B /  53.69  GB    512   B +  0 B   1.0
/dev/nvme1n1     AWS66337A23B237EFE14 Amazon EC2 NVMe Instance Storage         1         300.00  GB / 300.00  GB    512   B +  0 B   0
```

```
core@ip-10-149-64-41 ~ $ df -h
Filesystem       Size  Used Avail Use% Mounted on
...
/dev/nvme1n1     275G   65M  260G   1% /var/lib/docker
...

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
