### PR TITLE
Pull prod metrics-server image

### PR DESCRIPTION
**Pull request by mikkeloscar**
Pull prod image instead of staging image.

### CODE REVIEW

**Comment by katyanna** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by myaser** [comment]
there is another one
https://github.com/zalando-incubator/kubernetes-on-aws/search?q=container-registry-test

**Comment by mikkeloscar** [comment]
@myaser Added!

**Comment by myaser** [comment]
👍🏻

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
