### PR TITLE
Updated emergency access service tag

### PR DESCRIPTION
**Pull request by gargravarr**
New image replaces `debug` access with `manual`.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@gargravarr Please also update the version labels in the manifest.

**Comment by gargravarr** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Comment by gargravarr** [comment]
@mikkeloscar updated

**Comment by gargravarr** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
