### PR TITLE
Update deployment-service to allow for configuring mustache templating

### PR DESCRIPTION
**Pull request by linki**
Update deployment-service to include https://github.bus.zalan.do/teapot/deployment-service/pull/211 and configure it similar to the current behaviour for now.

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by linki** [comment]
Waiting for @tcondeixa to approve.

**Comment by tcondeixa** [comment]
👍

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
