### PR TITLE
update: skipper opa improvements [2/2]

### PR DESCRIPTION
**Pull request by szuecs**
waits for to be in stable https://github.com/zalando-incubator/kubernetes-on-aws/pull/8067

### CODE REVIEW

**Comment by szuecs** [comment]
:+1:

**Comment by demonCoder95** [comment]
Do we want to wait for canary update in #8067 to rollout to `stable` before merging this?

**Comment by szuecs** [comment]
@demonCoder95 yes

**Comment by demonCoder95** [comment]
👍

**Pull request merged**
