### PR TITLE
update stackset-controller's e2e test and enable configmap support in e2e tests

### PR DESCRIPTION
**Pull request by linki**
This updates StacksetController's e2e to the latest version and enables versioned ConfigMap support during e2e test runs.

### CODE REVIEW

**Comment by gargravarr** [comment]
I think you will need to set ConfigMap support here: https://github.com/zalando-incubator/kubernetes-on-aws/blob/dev/test/e2e/cluster_config.sh#L10

**Comment by linki** [comment]
This can also be handled by putting it in the defaults for the e2e environment: https://github.com/zalando-incubator/kubernetes-on-aws/pull/6780/files#diff-d2b7fb562825d0d0a4261e91eb9f214a1fefbc247b40666e0b976213473389c5R880

**Comment by mikkeloscar** [comment]
:+1:

**Comment by katyanna** [comment]
:+1:

**Pull request merged**
