### PR TITLE
Implement feature toggle to move the logging agent to visibility namespace

### PR DESCRIPTION
**Pull request by astarnell**
- Wrap all namespace configurations for logging-agent with feature toggle
- Add new visibility-logging PriorityClass
- Change updateStrategy for logging-agent to RollingUpdate
- Add logging-agent DaemonSet to deletions.yaml for the not used namespace

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Could you also add `post_apply` deletions for other components (configmap, secret, etc)?

**Comment by astarnell** [comment]
> Could you also add `post_apply` deletions for other components (configmap, secret, etc)?

I added logging-agent Secret, logging-agent ServiceAccount, logging-agent-privileged-psp RoleBinding and fluentd-config ConfigMap to post_apply

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
