### PR TITLE
Bump to kubernetes v1.6.6

### PR DESCRIPTION
**Pull request by mikkeloscar**
* Updates to Kubernetes v1.6.6
* Updates kube-dns (part of v1.6.5)

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v166
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#v165

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
What is the reason for this change, if it's only mentioning one google issue?

**Comment by mikkeloscar** [comment]
> What is the reason for this change, if it's only mentioning one google issue?

See link above to v1.6.5 CHANGELOG + kube-dns update.

**Comment by szuecs** [comment]
> See link above to v1.6.5 CHANGELOG + kube-dns update.

Maybe the deeplink is wrong, but I see no value in the posted CHANGELOGs for us

**Comment by mikkeloscar** [comment]
@szuecs 

Yeah, you have to scroll down below all the download links to see the full CHANGELOG since v1.6.4. Here is a deeplink: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v164

**Comment by szuecs** [comment]
Oh indeed there are some interesting fixes including api-server stabiilty, kube-proxy leaked iptables chains

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
