### PR TITLE
Kubelet: use authenticated API by default [2/3]

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Update API server & metrics-server to use the secure Kubelet endpoint.

**NOTE**: do not merge until #2153 is fully rolled out.

### CODE REVIEW

**Comment by njuettner** [comment]
Suggestion to disable it on kubelet is to set it to `-read-only-port 0` or is there anything else which needs this readonly port to be open?

**Comment by mikkeloscar** [comment]
> Suggestion to disable it on kubelet is to set it to -read-only-port 0 or is there anything else which needs this readonly port to be open?

We just need to do it in two steps. We disable it in #2170 : https://github.com/zalando-incubator/kubernetes-on-aws/pull/2170/files#diff-8f1eda593049fa31a03c0238a0135008L293

**Comment by mikkeloscar** [comment]
@aermakov-zalando I updated prometheus to use the secure kubelet port and also changed the apiserver scraping to use 443 instead of the readonly nginx address.

**Comment by szuecs** [comment]
@mikkeloscar do we have zmon checks that go directly through the readonly nginx ?

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
👍

**Comment by aermakov-zalando** [comment]
@mikkeloscar Thanks!

**Comment by mikkeloscar** [comment]
@szuecs yes, I think we still have some ZMON checks using the nginx endpoint. @aermakov-zalando and I talked about getting rid of the nginx proxy, but we didn't really look into how much depend on it yet. But at least prometheus no longer depends on it :)

**Pull request merged**
