### PR TITLE
Add support for customizable AZs

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Use `.Values.availability_zones` instead of using `subnets` or just hardcoding. Depends on https://github.com/zalando-incubator/cluster-lifecycle-manager/pull/140.

### CODE REVIEW

**Comment by hjacobs** [comment]
What's the background for this configuration option? Why do we need it?

**Comment by aermakov-zalando** [comment]
@hjacobs A few instance types are not available in some of the AZs. LaunchTemplates perform extensive validation, so this prevents us from even creating the CF stack for the cluster, because it's hardcoded to use all 3.

**Comment by njuettner** [comment]
👍

**Comment by patandrick** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
