### PR TITLE
Skipper/routesrv2 [2/2]

### PR DESCRIPTION
**Pull request by szuecs**
needs to wait for https://github.com/zalando-incubator/kubernetes-on-aws/pull/4692 to be merged and then wait for [1/2] https://github.com/zalando-incubator/kubernetes-on-aws/pull/4702 to be in stable

### CODE REVIEW

**Comment by marcinzaremba** [comment]
Besides I would also enable tracing straight away here to have a visibility into polling/serving latency and error rate.

**Comment by szuecs** [comment]
@marcinzaremba feel free to add it, but it's also fine to deploy this without opentracing. The most important thing is to monitor container metrics and check the dashboard for restarts.
Important is to create a new opentracing token for this service.

**Comment by szuecs** [comment]
:+1:

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
