### PR TITLE
Update kube-metrics-adapter to fix ZMON collector and Skipper metrics with some missing hosts

### PR DESCRIPTION
**Pull request by mikkeloscar**
PRs:
1. https://github.com/zalando-incubator/kube-metrics-adapter/pull/48
2. https://github.com/zalando-incubator/kube-metrics-adapter/pull/47
3. https://github.com/zalando-incubator/kube-metrics-adapter/pull/50

### CODE REVIEW

**Comment by arjunrn** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@arjunrn I have one question/concern about zalando-incubator/kube-metrics-adapter#47. Before it would fail on any error, but now, what would happen if we get an error from what would normally be the max and we then choose a lower metric? Say an ingress has two hostnames and the main hostname fails because of a connection issue to prometheus, but the second hostname with `0 rps` succeeds because the connection works when that call is made?

**Comment by arjunrn** [comment]
@mikkeloscar The fix was meant for the opposite situation. What was happening is that the metrics are only created on the fly. So there won't be metrics for hosts which are not being called. But there will be for ones which are but the adapter would return an error anyway. I've not fixed the adapter and created a [PR](https://github.com/zalando-incubator/kube-metrics-adapter/pull/50) to only ignore invalid result errors.

**Comment by mikkeloscar** [comment]
@arjunrn awesome!

**Comment by mikkeloscar** [comment]
@arjunrn updated the image

**Comment by arjunrn** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
