### PR TITLE
Update AMI to containerd (Kube 1.23)

### PR DESCRIPTION
**Pull request by linki**
Equivalent of https://github.com/zalando-incubator/kubernetes-on-aws/pull/5869 but towards kube-1.23

This updates the AMI to the latest version that has been tested to work. This is to test the new AMI against the e2e testing we have in this repository.

More details on [this PR](https://github.bus.zalan.do/teapot/kubernetes-on-ubuntu/pull/169) in `kubernetes-on-ubuntu` repo.

### CODE REVIEW

**Comment by demonCoder95** [comment]
Added missing log rotation parameters to the kubelet config.

**Comment by demonCoder95** [comment]
Set the override on `teapot` to be able to test logging-agent.

**Comment by demonCoder95** [comment]
Setting override to `stups-test` now, to finish rollout to `dev`.

Update: Couldn't set the override and had to merge the AMI PR and use the production image for it. Waiting for pipeline to become green again and will then set the override on `stups-test`.

Update: Rollout to `stups-test` complete. `dev` channel is now on containerd. 🚀

**Comment by linki** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Comment by gargravarr** [comment]
:+1:

**Pull request merged**
