### PR TITLE
Upgrade zmon-agent 0.1-a42

### PR DESCRIPTION
**Pull request by mohabusama**
Changes:

- Discover namespace entities
- Fix a namespace caching bug
- Update postgresql discovered entities

### CODE REVIEW

**Comment by mohabusama** [comment]
@linki @mikkeloscar I assume the e2e tests cover zmon entities discovery, correct?

**Comment by szuecs** [comment]
@mohabusama no, but you can provide them :)

**Comment by mohabusama** [comment]
@szuecs fair enough :)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
