### PR TITLE
Update skipper version, step 1/2

### PR DESCRIPTION
**Pull request by RomanZavodskikh**
+ https://github.com/zalando/skipper/pull/3227
+ https://github.com/zalando/skipper/pull/3225
+ https://github.com/zalando/skipper/pull/3234
+ https://github.com/zalando/skipper/pull/3239
+ https://github.com/zalando/skipper/pull/3240
+ https://github.com/zalando/skipper/pull/3241
+ https://github.com/zalando/skipper/pull/3242
+ https://github.com/zalando/skipper/pull/3245
+ https://github.com/zalando/skipper/pull/3246
+ https://github.com/zalando/skipper/pull/3247
+ https://github.com/zalando/skipper/pull/3249
+ https://github.com/zalando/skipper/pull/3248

FYI https://github.com/zalando/skipper/compare/v0.21.198...v0.21.208

### CODE REVIEW

**Comment by szuecs** [comment]
@RomanZavodskikh please also add flags and config item to set the new introduced server handler settings to configure closing connections.

**Comment by AlexanderYastrebov** [comment]
Lets consider https://github.com/zalando-incubator/kubernetes-on-aws/pull/8193 as an alternative.

**Comment by demonCoder95** [comment]
Closing this in favor of #8205 created by the bot.

**Comment by RomanZavodskikh** [comment]
I have rebased the branch and I had to create another PR to merge it:
https://github.com/zalando-incubator/kubernetes-on-aws/pull/8214

**Comment by RomanZavodskikh** [comment]
I have rebased this branch and that's why I have to create another PR to merge it:
https://github.com/zalando-incubator/kubernetes-on-aws/pull/8214

**Pull request closed without merging**
