### PR TITLE
add appropriate RBAC for the role-sync-controller

### PR DESCRIPTION
**Pull request by demonCoder95**
Since we removed the permissions to read `Secret` objects from the `poweruser` `ClusterRole` in #8537 , we can no longer bind this `ClusterRole` to the role-sync-controller `ServiceAccount`. This doesn't work anymore:

```golang
time="2024-12-09T08:53:00Z" level=error msg="error reconcile Role 'secrets-reader' for Namespace 'authorization-219': failed to create Role 'secrets-reader' in Namespace 'authorization-219': roles.rbac.authorization.k8s.io \"secrets-reader\" is forbidden: user \"system:serviceaccount:kube-system:role-sync-controller\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:kube-system\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"secrets\"], Verbs:[\"get\" \"list\" \"watch\"]}"
```

This introduces a new `ClusterRole` intended to be used by the role-sync-controller` and only provides the permissions it needs for syncing `secrets-reader` Role in each namespace.

### CODE REVIEW

**Comment by demonCoder95** [comment]
This change will be a `no-op` for `dev` since we enable the `role-sync-controller` only for the EKS provider. The change is tested in #8588 . Once that succeeds, we can merge this PR.

**Comment by demonCoder95** [comment]
👍

**Comment by demonCoder95** [comment]
The test in the other PR now works, we can merge this.

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
