### PR TITLE
AuditTrail S3 fallback

### PR DESCRIPTION
**Pull request by aermakov-zalando**
* Create an S3 bucket for AuditTrail fallback
 * Create an IAM role for Emergency Access Service

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by mikkeloscar** [comment]
Is the intention to use the same bucket for audittrail adapter at some point, or should it be named something with emergency-access-service?

We only need this enabled in production clusters because nothing that uses audittrail is running in test clusters

**Comment by aermakov-zalando** [comment]
I'd use one bucket for all applications. We could also provide a fallback sidecar for the users' applications that'll use this bucket automagically.

It's easier to create it like this (and then use for e.g. staging deployments), and the buckets don't really cost anything, but I can also template it if you think it's worth doing.

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
