### PR TITLE
Always set the CLC labels

### PR DESCRIPTION
**Pull request by aermakov-zalando**
This makes the switch a lot less annoying since the labels would already be in place.

### CODE REVIEW

**Comment by szuecs** [comment]
Why this is not targeting `dev` channel first and use `dev-to-kube-1.12` to propagate?

**Comment by aermakov-zalando** [comment]
@szuecs Because I want to avoid yet another rolling node update so we can just piggy-back on top of 1.12.

**Comment by aermakov-zalando** [comment]
👍

**Comment by linki** [comment]
:+1:

**Pull request merged**
