### PR TITLE
beta-to-stable

### PR DESCRIPTION
**Pull request by szuecs**
* **alpha-to-beta**
   <sup>Merge pull request #1909 from zalando-incubator/alpha-to-beta</sup>
* (No message)
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **Update CLC to master-4**
   <sup>Merge pull request #1908 from zalando-incubator/cherry-pick-clc-to-alpha</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **dev-to-alpha**
   <sup>Merge pull request #1904 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Fix/redis based csluterratelimits**
   <sup>Merge pull request #1900 from zalando-incubator/fix/redis-based-csluterratelimits</sup>
* **Update skipper with redis based cluster rate limiting**
   <sup>Merge pull request #1898 from zalando-incubator/update-skipper</sup>
* **Disabled acces log by default**
   <sup>Merge pull request #1886 from zalando-incubator/disable-skipper-access-logs</sup>
* **Update CLC**
   <sup>Merge pull request #1896 from zalando-incubator/update-clc</sup>
* **Ndots kube system**
   <sup>Merge pull request #1875 from zalando-incubator/ndots-kube-system</sup>
* **alpha-to-beta**
   <sup>Merge pull request #1895 from zalando-incubator/alpha-to-beta</sup>
* **Signed-off-by: Mikkel Oscar Lyderik Larsen <mikkel.larsen@zalando.de>
  **
   <sup>Merge branch 'alpha' into alpha-to-beta</sup>
* **Dev to alpha**
   <sup>Merge pull request #1894 from zalando-incubator/dev-to-alpha</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into dev-to-alpha</sup>
* **Default teapot_admission_controller_process_resources to false**
   <sup>Merge pull request #1892 from zalando-incubator/fix-default-process-resources</sup>
* **Enable Teapot admission controller for test clusters**
   <sup>Merge pull request #1891 from zalando-incubator/enable-admission-control</sup>
* **Signed-off-by: Alexey Ermakov <alexey.ermakov@zalando.de>
  **
   <sup>Merge branch 'dev' into ndots-kube-system</sup>
* **Signed-off-by: njuettner <nick@zalando.de>
  **
   <sup>Merge branches 'dev' and 'ndots-kube-system' of github.com:zalando-incubator/kubernetes-on-aws into ndots-kube-system</sup>

### CODE REVIEW

**Comment by mikkeloscar** [comment]
Blocked until the skipper disable-access-log flag is clarified, currently it disables all access logs including 4xx/5xx which is not intended.

**Comment by szuecs** [comment]
@mikkeloscar I reverted 5baa14dd32c03fd73ee13a06db4e20ec24257e38 to get rid of the default logging change

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
