### PR TITLE
Fix syntax for IAM permissions

### PR DESCRIPTION
**Pull request by linki**
CLM raises an error currently. I suspect the syntax is wrong here: https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874/files

Let's see.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
Not sure what the issue is here. I think `dev` is broken so it might already fail when creating the "base" cluster. We didn't catch that because https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874 didn't run any e2e tests. It's visible in dev-to-alpha though (https://github.com/zalando-incubator/kubernetes-on-aws/pull/4902).

Or maybe the issue is somewhere else.

**Comment by mikkeloscar** [comment]
Reverted the whole change here: #4906

**Comment by linki** [comment]
@msooszalando FYI, we had to revert https://github.com/zalando-incubator/kubernetes-on-aws/pull/4874 because of some syntax or semantics error with the changed policy.

**Comment by linki** [comment]
New attempt with e2e tests: https://github.com/zalando-incubator/kubernetes-on-aws/pull/4908

**Pull request closed without merging**
