### PR TITLE
[deployment-service] update cdpdeploymenttaskresource phases in CRD

### PR DESCRIPTION
**Pull request by demonCoder95**
Update the CDPDeploymentTask CRD to include the cdp task resource phases.

### CODE REVIEW

**Comment by linki** [comment]
👍

**Comment by demonCoder95** [comment]
Thanks for the fix, I missed that 🫠

**Comment by demonCoder95** [comment]
e2e is failing because of the skipper rollback that's in progress. Once done, will retrigger again.

**Comment by linki** [comment]
I added another `deployment-service` update and merged-in `dev` which contains an e2e fix. Let's 🤞

**Comment by demonCoder95** [comment]
A conformance test failed in e2e, doesn't seem related to the patch. I just retried the step.

**Comment by demonCoder95** [comment]
Still same failures

```
Summarizing 2 Failures:
  [FAIL] [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook [BeforeEach] should execute poststart exec hook properly [NodeConformance] [Conformance] [sig-node, NodeConformance, Conformance]
  /workspace/test/e2e/e2e_modules/kubernetes/test/e2e/framework/pod/pod_client.go:106
  [FAIL] [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook [BeforeEach] should execute poststart http hook properly [NodeConformance] [Conformance] [sig-node, NodeConformance, Conformance]
  /workspace/test/e2e/e2e_modules/kubernetes/test/e2e/framework/pod/pod_client.go:106
```

**Comment by demonCoder95** [comment]
Seems like they were temporary errors because of too many e2e pipelines running.

**Comment by demonCoder95** [comment]
👍

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
