### PR TITLE
Upgrade zmon aws agent and worker

### PR DESCRIPTION
**Pull request by mohabusama**
- AWS agent needs some fixes for AWS api calls and entities serialization
- Worker has the latest changes

### CODE REVIEW

**Comment by hjacobs** [comment]
What exactly is in this PR?

**Comment by mohabusama** [comment]
``zmon-aws-agent`` fixes:

- Handle RequestLimitExceeded in retries
- Enable retrieval of instance events
- Entities json serialization error (fixed in zmon-cli)

``zmon-worker``:

- Latest extra wrappers (saml2 and openam)

**Comment by hjacobs** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Pull request merged**
