### PR TITLE
Minor doc updates

### PR DESCRIPTION
**Pull request by muaazsaleem**
Updating minor things as I go through the docs

### CODE REVIEW

**Comment by hjacobs** [comment]
great, thanks!

**Comment by hjacobs** [comment]
:+1:

**Comment by szuecs** [comment]
@muaazsaleem what is missing to merge?

**Comment by muaazsaleem** [comment]
> @muaazsaleem what is missing to merge?

I think we can merge now, was improving docs as I was going through them. (Will create a new PR for future updates)

**Comment by szuecs** [comment]
:+1:

**Comment by muaazsaleem** [comment]
👍

**Comment by njuettner** [comment]
👍

**Pull request merged**
