### PR TITLE
update appdynamics logging component to v0.9

### PR DESCRIPTION
**Pull request by linki**
this update watches the `application` and `version` labels

### CODE REVIEW

**Comment by hjacobs** [comment]
We should probably rename to `appdynamics-agent`?

**Comment by hjacobs** [comment]
@linki are you renaming it?

**Comment by linki** [comment]
on it

**Comment by linki** [comment]
also renamed the daemonset itself for consistency

**Comment by mohabusama** [comment]
👍

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
