### PR TITLE
skipper remove hyperkube

### PR DESCRIPTION
**Pull request by ideahitme**
need testing

### CODE REVIEW

**Comment by ideahitme** [comment]
need to wait for the new release on skipper created, will update this PR to use the pathfinder/skipper new release image and add the label right after that

**Comment by hjacobs** [comment]
So @aryszka releases a new Skipper version, right?

**Comment by ideahitme** [comment]
@hjacobs @aryszka already release 0.9.15

**Comment by hjacobs** [comment]
This won't work, Docker image looks wrong and does not have the necessary arg:

```
docker run -it registry.opensource.zalan.do/pathfinder/skipper:v0.9.15 skipper -kubernetes -kubernetes-in-cluster
flag provided but not defined: -kubernetes
Usage of skipper:
  -access-log string
    	output file for the access log, When not set, /dev/stderr is used
  -access-log-disabled
    	when this flag is set, no access log is printed
  -address string
    	network address that skipper should listen on (default ":9090")
  -application-log string
    	output file for the application log. When not set, /dev/stderr is used
  -application-log-level string
    	log level for application logs, possible values: PANIC, FATAL, ERROR, WARN, INFO, DEBUG (default "INFO")
  -application-log-prefix string
    	prefix for each log entry (default "[APP]")
  -backend-flush-interval duration
    	flush interval for upgraded proxy connections (default 20ms)
  -close-idle-conns-period string
    	period of closing all idle connections in seconds or as a duration string. Not closing when less than 0 (default "20")
  -debug-gc-metrics
    	enables reporting of the Go garbage collector statistics exported in debug.GCStats
  -debug-listener string
    	when this address is set, skipper starts an additional listener returning the original and transformed requests
  -dev-mode
    	enables developer time behavior, like ubuffered routing updates
  -enable-profile
    	enable profile information on the metrics endpoint with path /pprof
  -etcd-prefix string
    	path prefix for skipper related data in etcd (default "/skipper")
  -etcd-urls string
    	urls of nodes in an etcd cluster, storing route definitions
  -experimental-upgrade
    	enable experimental feature to handle upgrade protocol requests
  -idle-conns-num int
    	maximum idle connections per backend host (default 64)
  -innkeeper-auth-token string
    	fixed token for innkeeper authentication
  -innkeeper-post-route-filters string
    	filters to be appended to each route loaded from Innkeeper
  -innkeeper-pre-route-filters string
    	filters to be prepended to each route loaded from Innkeeper
  -innkeeper-url string
    	API endpoint of the Innkeeper service, storing route definitions
  -insecure
    	flag indicating to ignore the verification of the TLS certificates of the backend services
  -kubernetes-healthcheck
    	automatic healthcheck route for internal IPs with path /kube-system/healthz; valid only with kubernetes-url (default true)
  -kubernetes-url string
    	kubernetes API base url for the ingress data client; when set, it enables ingress
  -metrics-listener string
    	network address used for exposing the /metrics endpoint. An empty value disables metrics. (default ":9911")
  -metrics-prefix string
    	allows setting a custom path prefix for metrics export (default "skipper.")
  -oauth-credentials-dir string
    	directory where oauth credentials are stored: client.json and user.json
  -oauth-scope string
    	the whitespace separated list of oauth scopes
  -oauth-url string
    	OAuth2 URL for Innkeeper authentication
  -proxy-preserve-host
    	flag indicating to preserve the incoming request 'Host' header in the outgoing requests
  -routes-file string
    	file containing static route definitions
  -runtime-metrics
    	enables reporting of the Go runtime statistics exported in runtime and specifically runtime.MemStats (default true)
  -serve-host-metrics
    	enables reporting total serve time metrics for each host
  -serve-route-metrics
    	enables reporting total serve time metrics for each route
  -source-poll-timeout int
    	polling timeout of the routing data sources, in milliseconds (default 3000)
  -tls-cert string
    	the path on the local filesystem to the certificate file (including any intermediates)
  -tls-key string
    	the path on the local filesystem to the certificate's private key file
  -version
    	print Skipper version

**Comment by aryszka** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
