### PR TITLE
Give deployment role permissions for almost everything

### PR DESCRIPTION
**Pull request by mikkeloscar**
Give deployment role permissions for almost everything, to enable deployment of any resources supported via cloudformation.

This is based on the role we have for autobahn which is maybe to relaxed. @tuxlife do you see any obvious permissions we can drop from this?

### CODE REVIEW

**Review by tuxlife — CHANGES_REQUESTED** [review]
You allow for example iam:CreateUser. Can we use the PowerUser role as template?

**Comment by mikkeloscar** [comment]
@tuxlife changed to use the same permissions as `PowerUser`.

**Review by tuxlife — APPROVED** [review]

**Comment by tuxlife** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:-1:

**Comment by mikkeloscar** [comment]
Don't merge yet!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by ideahitme** [comment]
👍

**Pull request merged**
