### PR TITLE
Use gp3 for the root volume

### PR DESCRIPTION
**Pull request by aermakov-zalando**
It's cheaper and provides much better baseline performance, no reason not to switch.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
Doesn't seem to be supported in CF at the moment. 🤷‍♂️

**Comment by mikkeloscar** [comment]
This is the CF error:

```
You must use a valid fully-formed launch template. Volume of size 30GB is smaller than snapshot 'snap-0194da2e1369f5937', expect size >= 50GB (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 560d3ecc-bcd0-4130-8185-b4a1c739a8ff; Proxy: null)
```

**Comment by aermakov-zalando** [comment]
@mikkeloscar They must've fixed it, let's see if it works with the correct size.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
