### PR TITLE
remove ssh key for yerken

### PR DESCRIPTION
**Pull request by ideahitme**
Dropping my ssh keys, please make sure to update all channels in the time you find appropriate :)

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by Raffo** [comment]
Test failed, please wait for retrigger, there are a bunch of tests in progress.

**Comment by aermakov-zalando** [comment]
Yeah, I think we have a bunch of issues right now with concurrent tests. :(

**Comment by Raffo** [comment]
Merging as it only failed during decommissioning.

**Comment by Raffo** [comment]
👍

**Pull request merged**
