### PR TITLE
Updated the zmon-scheduler and zmon-aws-agent images

### PR DESCRIPTION
**Pull request by arjunrn**
Updates the following ZMON components:

- `scheduler` - now runs as PID 1
- `aws-agent` - now reports validation method and status for ACM certs

### CODE REVIEW

**Comment by arjunrn** [comment]
👍

**Comment by aermakov-zalando** [comment]
@arjunrn ```$ docker pull registry.opensource.zalan.do/stups/zmon-scheduler:v46-41-g2c67dcb
Error response from daemon: manifest for registry.opensource.zalan.do/stups/zmon-scheduler:v46-41-g2c67dcb not found: manifest unknown: manifest unknown```

**Comment by arjunrn** [comment]
Fixed it @aermakov-zalando

**Comment by aermakov-zalando** [comment]
👍

**Comment by arjunrn** [comment]
:+1:

**Pull request merged**
