### PR TITLE
Documenting use of wait-for-healthcheck

### PR DESCRIPTION
**Pull request by muaazsaleem**
A follow up on: https://github.com/zalando-incubator/kubernetes-on-aws/pull/3322
Signed-off-by: Muaaz Saleem <muhammad.muaaz.saleem@zalando.de>

### CODE REVIEW

**Comment by muaazsaleem** [comment]
👍

**Comment by aermakov-zalando** [comment]
Could you undo the `go.sum` changes? They seem completely unrelated.

**Comment by muaazsaleem** [comment]
👍

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
