### PR TITLE
Merge dev to alpha

### PR DESCRIPTION
**Pull request by linki**
Notable changes:
* Adding ports needed for cross master communication (22 hours ago)
* chore(manifests): update ExternalDNS to v0.4.0 (2 days ago)
* chore: use images built by cdp all the way (5 days ago)
* fix: update image policy webhook to allow more images in e2e (2 days ago)
* add docker meetup berlin (5 days ago)
* chore: completely get rid of secretary :-( bye bye (5 days ago)
* feat: tell kubernetes how many master nodes it can expect (6 days ago)
* chore: update kubernetes to v1.6.7_coreos.0 (9 days ago)
* Added rreis keys (3 weeks ago)
* Replace secretary with a 'static' docker config. (3 weeks ago)

### CODE REVIEW

**Comment by szuecs** [comment]
Can we have the ingress controller fix in this PR, too?
It would be nice to fix the ALBs sooner than having to wait until next week to fix it for all the clusters

**Comment by mikkeloscar** [comment]
> Can we have the ingress controller fix in this PR, too?

Can't we just create a new PR when the ingress changes are ready? We don't have to wait several days to merge it even if it's not in this PR IMO.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
I agree with @mikkeloscar. I'm happy to create a follow-up PR as soon as it's ready @szuecs.

**Comment by linki** [comment]
👍

**Comment by linki** [comment]
one last manual test for the `prod` image policy.

**Comment by mikkeloscar** [comment]
:-1:

**Comment by linki** [comment]
We're going to double-check that all user provided images in the production clusters are compliant. Otherwise they will be torn down once this is merged.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by linki** [comment]
switched `policy` config item to `dev` so that all images are allowed as before. This way we can rollout and enforce policy later. Behaviour is like before til then.

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
