### PR TITLE
Dev to alpha

### PR DESCRIPTION
**Pull request by mikkeloscar**
* update ExternalDNS to v0.5.0-alpha.3
* Scrape metrics from kube-apiserver pods
* Open cadvisor port on master nodes
* Add readiness probe to prometheus
* Add support for spot worker instances

### CODE REVIEW

**Comment by mikkeloscar** [comment]
@linki I assume external-dns is good to go? :)

**Comment by mikkeloscar** [comment]
:+1:

**Comment by hjacobs** [comment]
:+1:

**Comment by linki** [comment]
@mikkeloscar yes

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
